### ISSUE TITLE
Build error on 3.2.1 stream

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#101]
We need to update Paho to the official build...

[streamsadmin@streamsqse streamsx.messaging-streams_3.2.1]$ ant
Buildfile: 
/home/streamsadmin/local-toolkits/streamsx.messaging-streams_3.2.1/build.xml

toolkit:

init:

maven-deps:
      [exec] [INFO] Scanning for projects...
      [exec] [INFO]
      [exec] [INFO] 
------------------------------------------------------------------------
      [exec] [INFO] Building com.ibm.streamsx.messaging 1.0.0
      [exec] [INFO] 
------------------------------------------------------------------------
      [exec] [WARNING] The POM for 
org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.0.1-SNAPSHOT is 
missing, no dependency information available
      [exec] [INFO] 
------------------------------------------------------------------------
      [exec] [INFO] BUILD FAILURE
      [exec] [INFO] 
------------------------------------------------------------------------
      [exec] [INFO] Total time: 0.402 s
      [exec] [INFO] Finished at: 2015-03-26T15:55:48-04:00
      [exec] [INFO] Final Memory: 6M/13M
      [exec] [INFO] 
------------------------------------------------------------------------
      [exec] [ERROR] Failed to execute goal on project 
streamsx.messaging: Could not resolve dependencies for project 
com.ibm.streamsx.messaging:streamsx.messaging:jar:1.0.0: Failure to find 
org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.0.1-SNAPSHOT in 
http://repository.apache.org/content/repositories/snapshots/ was cached 
in the local repository, resolution will not be reattempted until the 
update interval of apache.snapshots has elapsed or updates are forced -> 
[Help 1]
      [exec] [ERROR]
      [exec] [ERROR] To see the full stack trace of the errors, re-run 
Maven with the -e switch.
      [exec] [ERROR] Re-run Maven using the -X switch to enable full 
debug logging.
      [exec] [ERROR]
      [exec] [ERROR] For more information about the errors and possible 
solutions, please read the following articles:
      [exec] [ERROR] [Help 1] 
http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

BUILD FAILED
/home/streamsadmin/local-toolkits/streamsx.messaging-streams_3.2.1/build.xml:56: 
The following error occurred while executing this line:
/home/streamsadmin/local-toolkits/streamsx.messaging-streams_3.2.1/com.ibm.streamsx.messaging/build.xml:81: 
exec returned: 1

Total time: 2 seconds

**Comment by chanskw** [comment]
@conglisc  - please fix

**Comment by chanskw** [comment]
Please close when you have confirmed that the fix is ok and delivered correctly.

**Comment by conglisc** [comment]
Close this issue
