### ISSUE TITLE
KafkaConsumer operator gets Java NullPointerException for messages with no key 

### ISSUE THREAD

**Issue by wrmadden** [IBMStreams/streamsx.messaging#103]
when using the KafkaConsumer operator with a topic where the messages were produced with no key, you get a NullPointerException in AttributeHelper.setValue.  I believe changing the setValue routines to check for null will resolve:
...
void setValue(OutputTuple otup, String value) {
		if((!isAvailable) || (value == null)) return;
...
void setValue(OutputTuple otup, byte[] value) {
		if((!isAvailable) || (value == null)) return;
...

**Comment by Alex-Cook4** [comment]
Resolved.
