### ISSUE TITLE
Request for a subscribe/unsubscribe toggle in MQTTSource operator

### ISSUE THREAD

**Issue by blechner** [IBMStreams/streamsx.messaging#104]
It would be nice if there was a "subscribe/unsubscribe toggle" input port on MQTTSource operator. For instance, if that input port received a "toggle off" tuple (a boolean flag, maybe), then the MQTTSource would unsubscribe to all topics. If the port received a "toggle on" tuple, it would subscribe to all topics again.
I know that the MQTTSource operator supports removal and insertion of topics in runtime, but a simple flag to toggle subscribe/unsubscribe of all existing topics would make our lives easier.

**Comment by chanskw** [comment]
Yes, good idea!

**Comment by schubon** [comment]
Customers are already using the new toolkit https://github.com/IBMStreams/streamsx.mqtt
