### ISSUE TITLE
Committer Nomination:  Cong Li

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#106]
I would like to nominate Cong Li @conglisc to be a committer to the messaging project.

In the last few months, Cong has made high quality bug fixes to the messaging toolkit.  He has enabled SSL support for MQTT operators.  He has also completed consistent region implementation for the sink operators in the messaging toolkit.

In his contributions, Cong demonstrated good understanding of the messaging toolkit operators.

**Comment by mikespicer** [comment]
+1

**Comment by rohitsw** [comment]
+1

**Comment by ddebrunner** [comment]
+1

**Comment by chanskw** [comment]
Thanks for the speedy votes.

@conglisc , welcome to the messaging toolkit project!  Added you as committer.
