### ISSUE TITLE
Kafka Producer and Consumer should support multiple charsets

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#112]
Currently Kafka operators are built to support only utf-8. This should be expanded to support at least utf-16 and potentially more.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
