### ISSUE TITLE
KafkaConsumer gets an NPE processing received msgs that lack a key

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.messaging#114]
If a received msg lacks a key, msg.key() returns null, e.g., a message created by bin/kafka-console-producer.sh ... --topic mytopic, the consumer gets an NPE when processing the received msg... trying to create a String from a null value.  See the stacktrace from the kafka sample below.  

A fix would be to make AttributeHelper.setValue create an empty String for a null key.

You can recreate the problem by starting the kafka sample and then generating additional msgs using the kafka tool above.

04 Aug 2015 11:14:23.105 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:com.ibm.streamsx.messaging.kafka.KafkaClient$KafkaConsumer.run:-1]  -  Topic[mytopic] Thread[0] Could not send message
04 Aug 2015 11:14:23.105 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - java.lang.NullPointerException
04 Aug 2015 11:14:23.105 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - java.lang.String.<init>(String.java:2178)
04 Aug 2015 11:14:23.106 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - com.ibm.streamsx.messaging.kafka.AttributeHelper.setValue(AttributeHelper.java:81)
04 Aug 2015 11:14:23.106 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - com.ibm.streamsx.messaging.kafka.KafkaClient.newMessage(KafkaClient.java:145)
04 Aug 2015 11:14:23.106 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - com.ibm.streamsx.messaging.kafka.KafkaClient.access$000(KafkaClient.java:30)
04 Aug 2015 11:14:23.106 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - com.ibm.streamsx.messaging.kafka.KafkaClient$KafkaConsumer.run(KafkaClient.java:176)
04 Aug 2015 11:14:23.107 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - java.lang.Thread.run(Thread.java:809)
04 Aug 2015 11:14:23.107 [25697] ERROR #splapptrc,J[52],P[107],KafkaStream2 M[?:?:0]  - com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)

**Comment by Alex-Cook4** [comment]
This item as been fixed.
