### ISSUE TITLE
Shutdown handling for KakfaSource operator is incorrect.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#116]
The operator will call client.shutdown() but there is no synchronization, so it's not guaranteed that the threads running KafkaConsumer will see the shutdown request.

Instead KafkaConsumer should check its thread's interrupted flag, which will be set when shutdown is called.

As an aside, I found it confusing that KafkaConsumer was not in fact the KafkaConsumer from the Apache Kakfa project, but instead a class specific to this toolkit. I would suggest renaming it to avoid such confusion.

**Comment by chanskw** [comment]
Hi Dan - Do you want to rename the class or the operator name?

**Comment by dlaboss** [comment]
Dan, those are valid points, but I *suspect* it won't address the issue I'm seeing with shutdown processing in a java8 context.  i.e., looking at the trace that's present in this code and what I see generated in practice, I *suspect* that the "read" from the kafkaStream on KafkaClient:171 simply isn't returning, so it doesn't matter what's checked after that.

**Comment by ddebrunner** [comment]
@chanskw I meant the Java class KafkaConsumer, when I saw it being used I immediately assumed it was from Apache Kafka, and went there to look at its javadoc, and then saw it wasn't being closed so thought that was a resource leak. Until I figured out it was a different KafkaConsumer.

**Comment by Alex-Cook4** [comment]
Dan, the current code does a check on client.isShutdown(). Isn't that equivalent and allowing for synchronization? 

<pre>
	public void run() {
			logger.log(TraceLevel.INFO,baseMsg + "Thread Started");
			for(MessageAndMetadata<byte[], byte[]> ret : kafkaStream) {
				<strong>if(client.isShutdown()) break;</strong>
				if(logger.isLoggable(TraceLevel.DEBUG))
					logger.log(TraceLevel.DEBUG, baseMsg + "New Message");
				try {
					client.newMessage(topic, ret);
				} catch (Exception e) {
					if(logger.isLoggable(TraceLevel.ERROR))
						logger.log(TraceLevel.ERROR, baseMsg + "Could not send message", e);
				}
			}
			logger.log(TraceLevel.INFO,baseMsg + "Thread Stopping");
		}
</pre>

**Comment by Alex-Cook4** [comment]
@ddebrunner Isn't the above code equivalent since shutdown() will make client.isShutdown() true?

**Comment by Alex-Cook4** [comment]
We have moved to the Kafka 0.9 consumer now. The shutdown implementation is handled starting here: https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/kafka/KafkaConsumerV9.java#L121

So far we haven't had issues with stray consumers as in the past. Please take a look if you have a chance and see if you think there could be any improvements.

**Comment by chanskw** [comment]
Please resolve and confirm if shutdown is now implemented correctly.
