### ISSUE TITLE
Kafka multi topic producer works with java7 but not java8

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.messaging#118]
The application below works - generates and reports 10 msgs for each of testTopic1 and testTopic2 when run standalone in a java7 execution environment.  

When run standalone in a java8 execution environment, it only reports some (just the 1st two?) testTopic1 msgs and not report any of the testTopic2 msgs.  With java8 it also leaves an orphaned standalone process as described in issue#117.

Run `date` before you run it and ignore any msgs with an earlier timestamp in them.
  
See issue#117 on how to achieve building for 7 vs 8.

You need to create testTopic1 and testTopic2 - e.g., 
```
$(KAFKA_HOME)/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic testTopic1
$(KAFKA_HOME)/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic testTopic2
```
This uses the same properties files as needed to run the KafkaSample in your env.

```
namespace com.ibm.streamsx.messaging.sample.kafka;

use com.ibm.streamsx.messaging.kafka::*;

composite KafkaSampleMultiTopicProducer {
    graph
		stream<rstring topic, rstring key, rstring message> Topic1 = Beacon() {
			param
				iterations : 10 ;
				period : 1.0 ;
			output Topic1: topic = "testTopic1", message = ctime(getTimestamp())+" testTopic1 cnt="+(rstring)IterationCount(), key = "abc";
		}
		stream<rstring topic, rstring key, rstring message> Topic2 = Beacon() {
			param
				iterations : 10 ;
				period : 1.0 ;
			output Topic2: topic = "testTopic2", message = ctime(getTimestamp())+" testTopic2 cnt="+(rstring)IterationCount(), key = "abc";
		}
		() as KafkaSink = KafkaProducer(Topic1,Topic2) {
			param
				propertiesFile : "etc/producer.properties";
		}

	////////////////////////////////////////////////////
			
		stream<rstring topic, rstring key, rstring message> RcvdTopic1 = KafkaConsumer()
		{
			param
				propertiesFile : "etc/consumer.properties" ;
				topic : "testTopic1" ;
		}
		stream<rstring topic, rstring key, rstring message> RcvdTopic2 = KafkaConsumer()
		{
			param
				propertiesFile : "etc/consumer.properties" ;
				topic : "testTopic2" ;
		}
		() as RcvdSink = Custom(RcvdTopic1,RcvdTopic2 as RcvdMsgs)
		{
			logic
				onTuple RcvdMsgs : println("Message: " +(rstring) RcvdMsgs) ;
		}
}
```

**Comment by ddebrunner** [comment]
any idea if it works in distributed?

**Comment by ddebrunner** [comment]
and is this just a multiple topic issue, so a single topic works fine?

**Comment by dlaboss** [comment]
A single, single topic Source and Sink op in a job seems to work fine.  
Don't know about multiple single topic ops in a job.

For the above app running distributed:
- default/FNONE seems to work java8 or 7
- FALL seems to work with java7 but not with java8 -- seems like same results as standalone

**Comment by dlaboss** [comment]
Thinking it might have been more that it was the colocated consumers that were the real problem I tried more configs:
- 3 PEs:  Beacons&Producer, Consumers, Custom
  - FAILED w/java8 - expected since didn't think it was the coloc producer&consumers that was the issue
- 4 PEs: Beacons&Producer, Consumer1, Consumer2, Custom
  - FAILED w/java8 - hmm... expected this to work since I thought it might be coloc consumers that were the issue.  BTW verified via OffsetChecker tool that all msgs were sent and added to the logs.  So seemed to be just a consumer issue.  And verified worked w/java7.
- 4 PEs: Beacons, Producer, Consumers, Custom
  - FAILED w/java8 - so it wasn't just the coloc Beacons&Producer that was an issue
- 5 PEs: Beacons, Producer, Consumer1, Consumer2, Custom
  - WORKED w/java - expected since this is almost identical to FNONE

Given that both 4 PE configs failed and the 5 PE one didn't, it seems that there are two java8 related issues: one with coloc Beacons&Producer and one with coloc Consumers?

**Comment by Alex-Cook4** [comment]
I'm trying to run in distributed. No fusion yet. I'm getting strange behavior where about 50% of the time one of my consumers doesn't work. I'm wondering if it's some kind of race condition. This is using defaults in Streams Studio for 4.0.1. 

    25 Aug 2015 12:07:00.064 [9760] INFO #splapptrc,J[60],P[340],RcvdTopic2 M[Logging.scala:kafka.utils.Logging$class.info:68]  - Connected to g0601b01.pok.hpc-ng.ibm.com:9092 for producing
    25 Aug 2015 12:07:00.089 [9760] INFO #splapptrc,J[60],P[340],RcvdTopic2 M[Logging.scala:kafka.utils.Logging$class.info:68]  - Disconnecting from g0601b01.pok.hpc-ng.ibm.com:9092
    25 Aug 2015 12:07:00.106 [9763] INFO #splapptrc,J[60],P[340],RcvdTopic2 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [ConsumerFetcherThread-mygroup_d0710b06.pok.hpc-ng.ibm.com-1440518819562-a2e6ae45-0-2], Starting 
    25 Aug 2015 12:07:00.109 [9760] INFO #splapptrc,J[60],P[340],RcvdTopic2 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [ConsumerFetcherManager-1440518819642] Added fetcher for partitions ArrayBuffer([[testTopic2,0], initOffset 435 to broker id:2,host:g0601b03.pok.hpc-ng.ibm.com,port:9092] )
    25 Aug 2015 12:07:01.252 [9759] INFO #splapptrc,J[60],P[340],RcvdTopic2 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup_d0710b06.pok.hpc-ng.ibm.com-1440518819562-a2e6ae45], begin rebalancing consumer mygroup_d0710b06.pok.hpc-ng.ibm.com-1440518819562-a2e6ae45 try #0
    25 Aug 2015 12:07:01.314 [9759] INFO #splapptrc,J[60],P[340],RcvdTopic2 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [ConsumerFetcherManager-1440518819642] Stopping leader finder thread

**Comment by Alex-Cook4** [comment]
Here is the latest. I have updated the toolkit Kafka version to the most recent jar but that didn't make a difference. Here are the cases where I have no problem:
1. Locate consumers on separate hosts.
2. Give consumers different group names (which makes sense given they are reading from different topics)

@dlaboss I am trying to figure out if Kafka actually supports consumer groups reading from multiple different topics. All of the documentation I'm finding is about reading from a single topic, or multiple consumer groups reading from a single topic.

**Comment by dlaboss** [comment]
It seems pretty clear to me that Kafka supports multiple topics with a single group.  i.e., the group is an attribute of kafka's ConsumerConnector.  The consumer's topicMap defines what topics the consumer will receive with no mention of restrictions.  And kafka tracks offsets on a <group,topic> basis. 

Ah... here... the following example notes in the commentary (search for "but we could") it could have more https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Group+Example.  

Now, what would be different between that and my sample SPL code is that it would be doing it all in a single call to ConsumerConnector.createMessageStreams() whereas the SPL code, I believe, nets out to two separate ConsumerConnector instances, each with a single call createMessageStreams().  But even that seems ok as alluded to here https://cwiki.apache.org/confluence/display/KAFKA/FAQ (in talking about delayed msg handling in a single connector: "To address this issue, either making sure that all consumers can keep up, or using separate consumer connectors for different topics.").

I did try the scenarios multiple times, though probably some only a couple of times each so I may not have seen the pattern you've experienced.

"separate hosts" didn't seem to be a defining characteristic to me.  e.g., FNONE with all of the PEs on a single host did seem to consistently work for me.  Are you saying that you've seen that case fail too?

**Comment by Alex-Cook4** [comment]
To test my theory out further, I added a random sleep to the consumer code before we do a ConsumerConnector.createMessageStreams() call. I no longer have any problem, despite using the same consumer group name. 

To me, this means that it is an issue with the Kafka server not handling things correctly, or at least the kafka API not retrying things correctly. What do you think?

**Comment by dlaboss** [comment]
If you've convinced that separate SPL KafkaSource ops use completely independent threads/objects/kafka-objects then it would see like there's no other explanation than some concurrency issue in the Kafka API or server for this case.  Rather than a workaround including the vagueries of a random delay or any "long delay" (anything longer than a second?), maybe you could put the call to createStreamMessages into a per-group critical region -- just eliminate concurrency at that level?  and/or maybe the call to createConsumer() too for the same group?

**Comment by Alex-Cook4** [comment]
What do you mean by a "per-group" critical region? I don't think any kind of local locking will help with this. As far as I could find, Streams doesn't have locking mechanism that would be useful between operators. It sounds like a better idea than a random delay.

**Comment by dlaboss** [comment]
"per-group" meaning that concurrent use of the aforementioned kafka calls seemed ok when being performed on behalf of different consumer groups.  per-group synchronization is just an optimization.

Since / if the problem seems to only occur for multiple operators making those calls within the same PE then you could just try tweaking KafkaClient:
```synchronized void initConsumer() { ...
```
Of course if the problem really does happen even if the same-group ops are in separate PEs then that won't help.

**Comment by Alex-Cook4** [comment]
I have been seeing this in the case of seperate PEs as well. 

I think that I am going to use leader election in zookeeper to handle the synchronization.

**Comment by ddebrunner** [comment]
Has the issue been reported as an issue in kafka?

**Comment by Alex-Cook4** [comment]
I've done a lot of searching with no luck, but I'm not sure that there would be many people running into this.

**Comment by chanskw** [comment]
Is this resolved?  Is this really a case that Kafka does not work with Java 8?

**Comment by Alex-Cook4** [comment]
I tried this with the latest Kafka 0.9.0.1 clients and no longer see this issue. 

As with #125, I think this was mainly due to poor consumer group handling by Kafka that has improved dramatically in the latest releases. 

I am closing this as no longer an issue.
