### ISSUE TITLE
MQTTSource ERROR msg when terminating standalone application and stranded standalone process

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.messaging#124]
Can demonstrate it with the MQTT sample.
When ^C the standalone application, get an ERROR blurt.
This is with streamsx.messaging 2.0.1 / Streams v4.0.1.
Happens with java7 or 8.

@d0710b14:1110> peg JAVA_HOME  # using java7 
JAVA_HOME=/opt/ibm/java-x86_64-71
@d0710b14:1111> make standalone
/homes/hny2/dlaboss/builds/spreefp1-08jun/InfoSphere_Streams/4.0.1.0/bin/sc -a -t ../../com.ibm.streamsx.messaging:/homes/hny2/dlaboss/builds/spreefp1-08jun/InfoSphere_Streams/4.0.1.0/toolkits/com.ibm.streamsx.messaging -T -M application::MqttSample  --data-dir data
CDISP0727W WARNING: The ../../com.ibm.streamsx.messaging input path is not a directory.
Creating the types.
Creating the functions.
Creating the operators.
Creating the processing elements.
The standalone application is being created.
...
[Bundle] application.MqttSample.sab
@d0710b14:1112> psg standalone  # report all standalone processes - there are none
dlaboss  30425 31616  0 10:28 pts/23   00:00:00 egrep standalone

@d0710b14:1113> java -jar output/application.MqttSample.sab serverUri=localhost:1883
^C
The SIGINT signal occurred during the application execution. The application is shutting down.

@d0710b14:1114> 08 Sep 2015 10:29:14.951 [30582] ERROR #splapptrc,J[0],P[0],MyMessageStream M[MqttSourceOperator.java:com.ibm.streamsx.messaging.mqtt.MqttSourceOperator$2.run:323]  - Operator error

@d0710b14:1114> psg standalone  # the standalone process is still there
dlaboss  30521     1 30 10:28 pts/23   00:00:07 /tmp/3830908561877162857/output/bin/standalone serverUri=localhost:1883
dlaboss  30742 31616  0 10:29 pts/23   00:00:00 egrep standalone
@d0710b14:1115>

**Comment by conglisc** [comment]
Hi dlaboss,

I don't seen this issue anymore in 4.1 after several tests. Let me know if you still get this issue on 4.1.

make standalone SPL_CMD_ARGS=--data-directory=data
/homes/hny4/congli/SOPRIS/RH6/x86_64/eGA/4.1.0.0/bin/sc -a -t ../../com.ibm.streamsx.messaging:/homes/hny4/congli/SOPRIS/RH6/x86_64/eGA/4.1.0.0/toolkits/com.ibm.streamsx.messaging -T -M application::MqttSample --data-directory=data
CDISP0727W WARNING: The ../../com.ibm.streamsx.messaging input path is not a directory.
Creating the types.
Creating the functions.
Creating the operators.
Creating the processing elements.
The standalone application is being created.
Creating the application model.
Building the binaries.
 [CXX-type] tuple<int32 id,rstring fname,rstring lname,int32 age,rstr...score,float64 total>
 [CXX-type] tuple<blob data>
 [CXX-type] enum{csv,txt,bin,block,line}
 [CXX-operator] InputData
 [CXX-operator] FormatMsg
 [CXX-operator] MQTTSink_6
 [CXX-operator] MyMessageStream
 [CXX-operator] ParsedMsg
 [CXX-operator] MyMessageSink
 [CXX-pe] pe application.MqttSample-a
 [CXX-standalone] standalone
 [LD-standalone] standalone
 [LN-standalone] standalone 
 [LD-pe] pe application.MqttSample-a
 [Bundle] application.MqttSample.sab
-bash-4.1$ ps -elf | grep standalone
0 S congli   21890   734  0  80   0 - 25813 pipe_w 12:08 pts/2    00:00:00 grep standalone
-bash-4.1$ java -jar output/application.MqttSample.sab serverUri=tcp://localhost:16102
^CThe SIGINT signal occurred during the application execution. The application is shutting down.

-bash-4.1$ 11 Jan 2016 12:09:31.318 [22082] ERROR #splapptrc,J[0],P[0],MQTTSink_6 M[MqttSinkOperator.java:com.ibm.streamsx.messaging.mqtt.MqttSinkOperator$PublishRunnable.run:261]  - CDIST1554E Unable to publish message
11 Jan 2016 12:09:31.329 [22084] ERROR #splapptrc,J[0],P[0],MyMessageStream M[MqttSourceOperator.java:com.ibm.streamsx.messaging.mqtt.MqttSourceOperator$2.run:328]  - Operator error

-bash-4.1$ ps -elf | grep standalone
0 S congli   22120   734  0  80   0 - 25813 pipe_w 12:09 pts/2    00:00:00 grep standalone

**Comment by chanskw** [comment]
Closing, please reopen if you still see the issue.
