### ISSUE TITLE
Kafka Consumers without specified partitions starting in parallel often fail

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#125]
Kafka supports consumer groups which allow for many consumer threads to consume from the same topic. I am having trouble using parallel consumers (no partition specified) in Streams to consume from the same topic. I often get the following exceptions that lead to failures:

<pre>
Exception in thread "Thread-12" kafka.common.ConsumerRebalanceFailedException: mygroup4_d0301b14.pok.hpc-ng.ibm.com-1441925174996-4bd8d65c can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:630)
	at kafka.consumer.ZookeeperConsumerConnector.kafka$consumer$ZookeeperConsumerConnector$$reinitializeConsumer(ZookeeperConsumerConnector.scala:897)
	at kafka.consumer.ZookeeperConsumerConnector.consume(ZookeeperConsumerConnector.scala:239)
	at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreams(ZookeeperConsumerConnector.scala:85)
	at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreams(ZookeeperConsumerConnector.scala:97)
	at com.ibm.streamsx.messaging.kafka.KafkaClient.initConsumer(KafkaClient.java:141)
	at com.ibm.streamsx.messaging.kafka.KafkaSource.allPortsReady(KafkaSource.java:118)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.allPortsReady(OperatorAdapter.java:763)
	at com.ibm.streams.operator.internal.jni.JNIBridge.allPortsReady(JNIBridge.java:614)
</pre>

It seems like some other people have had to be careful about "restarting their kafka consumer to quickly after shutdown." That leads to think that there could be issues with having multiple separate consumers that are in the same consumer group (http://grokbase.com/t/kafka/users/133c6yw32v/consumerrebalancefailedexception). Then again, this seems like it should be supported. 

One solution is to set the parameter of the partition to read from for each partition.

**Comment by Alex-Cook4** [comment]
Resolving this requires upping the rebalance.max.retries and rebalance.backoff.ms because "When a new consumer joins a consumer group the set of consumers attempt to "rebalance" the load to assign partitions to each consumer. If the set of consumers changes while this assignment is taking place the rebalance will fail and retry. This setting controls the maximum number of attempts before giving up."

If you are trying to start 9 operators in parallel, the default value of 4 retries is most likely going to get exceeded. Especially with locking on the client startup implemented.

**Comment by Alex-Cook4** [comment]
https://github.com/SOHU-Co/kafka-node/issues/124
https://issues.apache.org/jira/browse/KAFKA-2331
https://issues.apache.org/jira/browse/KAFKA-242
https://issues.apache.org/jira/browse/KAFKA-1890
https://groups.google.com/forum/#!topic/secor-users/aFZ5_e7HXM4

<pre>
11 Sep 2015 14:26:57.586 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Cleared all relevant queues for this fetcher
11 Sep 2015 14:26:57.587 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Cleared the data chunks in all the consumer message iterators
11 Sep 2015 14:26:57.587 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Committing all offsets after clearing the fetcher queues
11 Sep 2015 14:26:57.588 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Releasing partition ownership
11 Sep 2015 14:26:57.616 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - Consumer mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603 rebalancing the following partitions: ArrayBuffer(0, 1, 2, 3, 4, 5, 6, 7, 8) for topic millionTupleTopic with consumers: List(mygroup10_d0119b11.pok.hpc-ng.ibm.com-1441996010141-67c99703-0, mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603-0, mygroup10_d0328b01.pok.hpc-ng.ibm.com-1441995984341-32ab9139-0)
11 Sep 2015 14:26:57.617 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603-0 attempting to claim partition 3
11 Sep 2015 14:26:57.617 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603-0 attempting to claim partition 4
11 Sep 2015 14:26:57.618 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603-0 attempting to claim partition 5
11 Sep 2015 14:26:57.620 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], end rebalancing consumer mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603 try #3
11 Sep 2015 14:26:57.621 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Rebalancing attempt failed. Clearing the cache before the next rebalancing operation is triggered
11 Sep 2015 14:26:57.621 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [ConsumerFetcherManager-1441996002462] Stopping leader finder thread
11 Sep 2015 14:26:57.622 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [ConsumerFetcherManager-1441996002462] Stopping all fetchers
11 Sep 2015 14:26:57.622 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [ConsumerFetcherManager-1441996002462] All connections stopped
11 Sep 2015 14:26:57.623 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Cleared all relevant queues for this fetcher
11 Sep 2015 14:26:57.623 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Cleared the data chunks in all the consumer message iterators
11 Sep 2015 14:26:57.624 [4674] INFO #splapptrc,J[1],P[12],KafkaConsumer_4 M[Logging.scala:kafka.utils.Logging$class.info:68]  - [mygroup10_d0301b11.pok.hpc-ng.ibm.com-1441996002307-9a86b603], Committing all offsets after clearing the fetcher queues
</pre>

**Comment by Alex-Cook4** [comment]
I think the solution to this may be to implement the new kafka consumer that is set to be released in October with improved rebalancing: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design

**Comment by chanskw** [comment]
Try this... in the consumer, add initDelay parameter.  The operator will only start after the initial delay.
Assign initial delay based on the channel.  e.g. 1sxgetChannel()... the schedules the operators to start sequentially.  This may not be a permanent solution.  But see if this works...

**Comment by Alex-Cook4** [comment]
I have tried offsetting the start times without success. I also went back and tried this with Streams 4.0 + messaging toolkit in 4.0 with the same results.

**Comment by Alex-Cook4** [comment]
A workaround that has worked for me several times in a row has been to have a new group.id property value each time I submit my job. It seems like something must not be getting cleaned up in zookeeper...

Using the same group.id repeatedly seems to lead to rebalancing issues. In general, Kafka's handling of rebalancing in the High Level Consumer has shown itself to be unreliable in my opinion. I wouldn't use this work-around because of significant risk in the case of operator restarts (since they will reuse the same group.id).

**Comment by dlaboss** [comment]
I haven't done anything w/multipartitioned topics but in my experience when a client doesn't rcv msgs and changing the group.id helps it's because an old client using the original group.id still exists.  That's exactly what happens due to #117.  (the Java Application API tests use that exact same create-a-new-group-id scheme to make themselves robust)  Of course it might be a different problem in your scenario. The ConsumerOffsetChecker tool can be helpful to see the state of things... if/who the topic partition leader is when you think there shouldn't be one.

**Comment by shasti86** [comment]
Hi Guys,
I am facing the same problem now. Is there a solution with having different group id al the time?

**Comment by Alex-Cook4** [comment]
The reliable work-around is: 

1. If you are parallel consuming, specify the partition you want to read from using the partition parameter in each consumer (you will need to have version 4.0.1 or later of the toolkit):
partition: 0; 
...
partition: 1;

If you are using an older version of the toolkit, there is not currently a known way to resolve this.

**Comment by chanskw** [comment]
has this been resolved?

**Comment by Alex-Cook4** [comment]
I have tested this out on Kafka 0.10 servers, using our latest Kafka 0.9.0.1 client and the issue is resolved. 

To summarize what was happening: 
Kafka consumer group rebalancing was not being done correctly by Kafka. --Part of this had to do with "dead" consumers continuing to be considered as part of the consumer group by Kafka, so they were getting partitions assigned to them (resulting in truly alive consumers not being assigned a partition). 

With the Kafka 0.9 and 0.10 releases, Kafka has improved the shutdown handling and cleanup of consumers that no longer exist from the group perspective. 

I am closing this as resolved.

**Comment by Alex-Cook4** [comment]
As a follow-up, I ran this with 16 consumers in parallel on a 10-partition topic and things worked as expected: 

Steps:

1. Launch 8 consumers in parallel: All consumers receiving messages, 2 consumers double the rest (they were assigned 2 partitions)
2. Launch 8 more consumers in parallel: 10 consumers receiving messages, 6 idle because they don't have any partitions assigned to them. 

The consumer rebalance failures are gone.
