### ISSUE TITLE
Committer Nomination:  Alex Cook

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#137]
I'd like to nominate Alex Cook @Alex-Cook4 to be a committer to the streamsx.messaging project.
In the past few months, Alex has been working on the Kafka operators in the messaging toolkit.  He has provided many quality bug fixes to the operators, re-architected the operators to make it more flexible and extensible.  He has also implemented the initial support for Kafka 0.9.

**Comment by petenicholls** [comment]
+1

**Comment by conglisc** [comment]
+1

**Comment by ddebrunner** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Thanks... Added Alex to be a committer to the messaging project.

Welcome Alex!
