### ISSUE TITLE
RabbitMQ: Make it possible to access jars without packaging in .sab

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#149]
In cases where we don't want the .sab to include RabbitMQ jars, we want to be able to set @Libraries with an environment variable. Not sure if this will work:

@Libraries({ "opt/downloaded/*", System.getEnv("rabbitMQ_lib") })

**Comment by Alex-Cook4** [comment]
That won't actually work, will need to do something similar to this: https://github.com/IBMStreams/streamsx.messaging/blob/d4932033b96c4a775c86c008f419a9cb145cd4db/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/jms/JmsClasspathUtil.java

**Comment by chanskw** [comment]
Try specifying a string like this:

"@RABBITMQ_HOME@/lib/*"

That should cause this string to be included in the generated operator model.  And then at runtime, have the environment variable resolved.

**Comment by chanskw** [comment]
I created a rabbitmq label, and you can tag all related issues with this new label.

**Comment by Alex-Cook4** [comment]
@chanskw "@RABBITMQ_HOME@/lib/*" works, but then it won't compile if it's not included. Do you know how I can make it optional?

**Comment by chanskw** [comment]
You mean if the environment variable is not set, then the application will not compile?

**Comment by Alex-Cook4** [comment]
Correct.

**Comment by Alex-Cook4** [comment]
I would like to be able to do: @Libraries({ "opt/downloaded/*", "@RABBITMQ_HOME@" }) and it will pull from whatever works.

**Comment by Alex-Cook4** [comment]
Delivered a version that does this for Streams 3.2.1, but do not use an environment variable for Streams 4+ versions of the toolkit. I have left in a commented out way to use an environment variable here: https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/rabbitmq/RabbitBaseOper.java#L30

To use this, uncomment that part of the code and rebuild your toolkit. Closing this as resolved.
