### ISSUE TITLE
Prebuilt toolkit not working on Streams version <4.0.1

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.messaging#165]
On 4.0.0 quick start VM, building KafkaSSLSample using the [Messaging Toolkit v4.0.0 Kafka 0.9 Alpha2 Release](https://github.com/IBMStreams/streamsx.messaging/releases/tag/v4.0.0-alpha2) results in the following exception:

Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/ibm/streamsx/messaging/kafka/KafkaSink, offset=6

The issue might be caused by the Java version inconsistency between 4.0.0 (Java 7) and 4.0.1 (Java 8). If so, resolution might involve building the toolkit with compatibility for earlier Java versions.

**Comment by ddebrunner** [comment]
FYI - the inet toolkit build sets the javac compile level at 6 to solve the same issue (though it could be updated to 7 for any toolkit that only supports 4.0 or later)

**Comment by ddebrunner** [comment]
I just did the same for the json toolkit

https://github.com/IBMStreams/streamsx.json/pull/42

and noticed that the setting was accidentally dropped in the inet toolkit.

**Comment by Alex-Cook4** [comment]
I believe this was fixed with release: https://github.com/IBMStreams/streamsx.messaging/releases/tag/v4.0.0-alpha3

@alexpogue Please also try and let us know if it worked. Thanks!

**Comment by alexpogue** [comment]
The latest release has fixed the issue. Closing issue.
