### ISSUE TITLE
Kafka Attributehelper setvalue method is unnecessarily complex

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#186]
With changes to parametrized clients, this can probably be simplified:

<pre>
    void setValue(OutputTuple otup, byte[] value) {
        if (!isAvailable)
            return;
        if (isString) {
            if (value == null)
                otup.setString(name, "");
            else
                otup.setString(name, new String(value, CS));
        } else {
            if (value != null) {
                otup.setBlob(name, ValueFactory.newBlob(value));
            }
        }
    }
</pre>

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
