### ISSUE TITLE
Message Hub requires a special JAR

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#204]
Currently, in order to use the messaging toolkit with Message Hub, you must download two extra JARs. This is not ideal as it requires the user to know this, and download and place them correctly. 

The danger of including the Message Hub "login" JAR in the release is that we do not have control over when/if Message Hub changes that JAR and we will have to keep trying to maintain compatibility.

**Comment by mikespicer** [comment]
Will Message Hub always require additional JARs or is this a temporary situation that they plan to resolve?

**Comment by chanskw** [comment]
Is this issue resolved?

**Comment by Alex-Cook4** [comment]
We will not package the Message Hub login JAR. Message Hub will eventually not require it if/when they move to 0.10. Closing.
