### ISSUE TITLE
SPL Doc does not reflect the latest operators

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#206]
The SPL Doc is for version 3.0 of the toolkit, which is the latest version of this toolkit in the product. Once we do a release of version 5.0, do we want to update the SPL Doc?

**Comment by chanskw** [comment]
Yes, SPLDoc needs to be updated.

**Comment by Alex-Cook4** [comment]
The Docs themselves are updated. We need to update the github io branch with the latest. I am removing must-fix tag.

**Comment by chanskw** [comment]
Sorry, I have to add this back.  I don't want to forget updating the spldoc when we are ready.
Can you please update the SPLDoc when you make a new release?

**Comment by Alex-Cook4** [comment]
Sure. Next release we should do that.

**Comment by ddebrunner** [comment]
bump - be good to have the online doc reflect the 5.0/5.1 toolkit.

**Comment by Alex-Cook4** [comment]
Fixed. Thanks @ddebrunner
