### ISSUE TITLE
RELEASE PROPOSAL:  4.x Branch Release proposal

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#207]
I would like to do a release of the 4.x branch. 
Reason: The 4.x branch now has extensively tested versions of RabbitMQ and Kafka. 

**Propose deletion of the following obsolete branches that were done for Message Hub:**
- v4.0.0
- v4.0.0-alpha3
- v4.0.0-alpha2
- v4.0.0-alpha

Title: Messaging Toolkit v4.0.0 Message Hub Release
Tag: v4.0.0
List of Enhancements: 
- Kafka 0.9 Support (with consistent region and parallel consuming capability)
- RabbitMQ Support

**This release does not support Kafka 0.8 servers.**

Please vote +1 to approve.

**Comment by ddebrunner** [comment]
Having so many versions of the toolkit with the same 4.0.0 version makes it very confusing.

**Comment by chanskw** [comment]
Is this request still valid?
Did we create a release without finishing a vote?

**Comment by Alex-Cook4** [comment]
There has not been a release. This request is still valid. I agree it is confusing, so I think doing this release and then deleting the other alphas will be helpful.

**Comment by ddebrunner** [comment]
Is it possible to ensure that the third element of the version is bumped when minor changes are made, there's no requirement for the official first release of a branch be 4.0.0.

**Comment by chanskw** [comment]
What version of Streams does this release support?

**Comment by chanskw** [comment]
The proposed deletions are releases, not branches, is that correct ?

**Comment by chanskw** [comment]
I echo what Dan has proposed, we need to bump the third digit on minor changes and not make up tags like alpha1 going forward. Can you please also indicate in your proposal the version number of this toolkit release ?

Thanks.

**Comment by ddebrunner** [comment]
I think tags (the qualifier) are valid, and github release does encourage their use for pre-releases, I just think the releases should have been something like

* v4.0.5
* v4.0.3-alpha3
* v4.0.1-alpha2
* v4.0.0-alpha

**Comment by Alex-Cook4** [comment]
Since this is from the 4.x branch, it is for Streams 4.0 (pre data-governance). 

I like the approach of making sure that we up the third digit of the version number for incremental changes. I am fine with making giving this release a v4.0.5 tag. 

Is there a good rule of thumb for when to up the third digit of the version number? Would adding a parameter to an operator fit that? Fixing a bug?

**Comment by ddebrunner** [comment]
See https://github.com/IBMStreams/administration/issues/5

Two releases of a toolkit must not have the same version number.

A bug fix should increase the third digit, new functionality that is backwards compatible should bump the second digit. Incompatible changes (that break existing applications) bump the first.

BTW 4.0.5 was just an example.

**Comment by chanskw** [comment]
For a 4.0 branch release, please bump version number to v4.0.1 if this release only includes minor bug fixes.

Please delete these alphas:
v4.0.0-alpha3
v4.0.0-alpha2
v4.0.0-alpha

Please leave the official v4.0.0 release.  This is a stable release and should not get deleted.

**Comment by Alex-Cook4** [comment]
I believe the version number should be bumped up to v4.1.0 as this release contains RabbitMQ which was not part of v4.0.0. 

+1 to keeping 4.0 branch since it was considered stable.

**Comment by chanskw** [comment]
ok... +1 to bump to v4.1.0.

Please summarize exactly what we are doing, so we are clear  and we can vote on the final proposal.

**Comment by Alex-Cook4** [comment]
****Updated Proposal****

Reason: The 4.x branch now has extensively tested versions of RabbitMQ and Kafka.

Title: Messaging Toolkit v4.1.0 Release
Tag: v4.1.0

List of Enhancements:
* Kafka 0.9 Support (with consistent region and parallel consuming capability)
* RabbitMQ Support

Propose deletion of the following obsolete branches that were done for Message Hub:
* v4.0.0-alpha3
* v4.0.0-alpha2
* v4.0.0-alpha

**Comment by chanskw** [comment]
To clarify, we are not deleting the branches / tags.

We are deleting the alpha releases, correct?

**Comment by Alex-Cook4** [comment]
Correct. That was a typo, I'll edit to say releases.

**Comment by chanskw** [comment]
+1 please release.

**Comment by schulz2** [comment]
This issue became irrelevant by history and changed build/release methods discussed elsewhere -> closing.
