### ISSUE TITLE
Issues with ant build - could not resolve dependencies.

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.messaging#208]
I'm using a 4.1 QSE, attempting to executing the ant command to build the toolkit, I'm getting the following error. 
   
`     [exec] [ERROR] Failed to execute goal on project streamsx.messaging: Could not resolve dependencies for project com.ibm.streamsx.messaging:streamsx.messaging:jar:1.0.0: Failure to find org.apache.activemq:activemq-client:jar:5.11-SNAPSHOT in http://repository.apache.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]`

Additional note: when I unpack their is no opt/downloaded directory to place: 
jackson-core-2.5.4.jar and messagehub.login-1.0.0.jar. After attempting the 
ant build, the directory is their.

**Comment by Alex-Cook4** [comment]
I also saw this error in my QSE too. @conglisc got it to work fine in other environments. I installed ant myself, so I thought that might have been the problem. 

As a side note, you shouldn't actually need the jackson-core-2.5.4.jar anymore. We are updating instructions to reflect that. 

Good point on opt/downloaded not being available until you do a build.

**Comment by conglisc** [comment]
Hi siegenth,

Are you trying to build the toolkit from master branch? I tried to build from master branch in QSE 4.1 environment, and I could not produce this issue.

ant works fine in my copy of QSE.

**Comment by conglisc** [comment]
Hi siegenth,

The problem should have been fixed by now, I have updated pom.xml file to use the latest activemq snapshot as the old one no longer exists.

Please pull the latest from master and try ant again.

Thanks
