### ISSUE TITLE
Cleansession for MQTT operators

### ISSUE THREAD

**Issue by chantalokh** [IBMStreams/streamsx.messaging#209]
Good morning,

We have a need to set sometimes the cleansession to false (for durable subscriptions and other needs), but i saw that it is forced to true,
line 52 of MqttClientWrapper.java, the clean session is always set to true
`conOpt.setCleanSession(true);` 
have you planned to put it as parameter of the operator?
Thanks
Amir

**Comment by ddebrunner** [comment]
Duplicate of #61

**Comment by ddebrunner** [comment]
This is probably a better description of the issue. I had previously thought that clean session was not supported and the operators default to durable, but they only support clean at the moment.

**Comment by schubon** [comment]
Customers are already using the new toolkit https://github.com/IBMStreams/streamsx.mqtt
