### ISSUE TITLE
ant target has failed SPL compile in tests

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#212]
Buildfile: /home/streamsadmin/quarks_iotf2/streamsx.messaging/tests/build.xml

kafka:
     [exec] make: Entering directory `/home/streamsadmin/quarks_iotf2/streamsx.messaging/tests/tests.kafka'
     [exec] /opt/ibm/InfoSphere_Streams/4.1.0.0/bin/sc -T -t ../../com.ibm.streamsx.messaging --output-directory ./output/BasicFunctionTestMain -M com.ibm.streamsx.messaging.kafka.tests::BasicFunctionTestMain
     [exec] make: Leaving directory `/home/streamsadmin/quarks_iotf2/streamsx.messaging/tests/tests.kafka'
     [exec] CDISP0384E ERROR: The tests.kafka toolkit requires version [3.0.0,4.0.0) of the com.ibm.streamsx.messaging toolkit, but version 5.0.0 of the required toolkit is currently installed.
     [exec] CDISP0131E ERROR: Errors occurred while the toolkits were loading.
     [exec] make: *** [BasicFunctionTestMain] Error 1
     [exec] Result: 2

all:

BUILD SUCCESSFUL
Total time: 6 seconds

Related to #187 and #211

**Comment by Alex-Cook4** [comment]
The tests need to be updated for the newer release versions. These specific tests haven't been looked at for a long time, so there may be cleanup required as well.

**Comment by Alex-Cook4** [comment]
I removed the tests directory because the tests were outdated (#222). I think that the true issue here is that we have not open sourced our JUnit tests.
