### ISSUE TITLE
Are pem files supported as a trust store format?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#215]
The MQTT element connection specifications states for the `trustStore` attribute:

> This optional attribute specifies the name of the truststore file, which is in PEM format. 

When I try specifying a pem file as the `trustStore` parameter to an MQTT operator I get this exception though:

`MqttException (0) - java.io.IOException: Invalid keystore format`

Do I need to create a java trust store that contains the pem file?

**Comment by ddebrunner** [comment]
Just to add the example of the xml connection document also shows a .pem file being used.

**Comment by conglisc** [comment]
Hi Dan,

The relevant SPLDoc was added with https://github.com/IBMStreams/streamsx.messaging/commit/6bb1524990bc22ffd5ebd40ecbee3a3157e44483#diff-59af699224428f30607ec34d9660cb9b

After doing some research, I don't think PEM is a supported keystore format in java out of box.

**Comment by conglisc** [comment]
Hi Dan,

Just want to confirm if I understand this question correctly.

Watson IOT server is not enforcing use of PEM format, but SPLDOC provides a sample using PEM file that makes you to think it is one of the supported format.

If this is true, I think SPLDOC requires a change.

Thanks

**Comment by ddebrunner** [comment]
@conglisc Correct, the sample shows a pem file being used which doesn't seem to be supported.

**Comment by ddebrunner** [comment]
Just to add Watson provides a pem file which I needed to load into a Java key store to work with these operators. See:

https://github.com/IBMStreams/streamsx.iot/blob/master/com.ibm.streamsx.iotf/opt/iotf/README.md

**Comment by conglisc** [comment]
ok, thanks @ddebrunner , I will modify the sample connection doc in SPLDOC.
