### ISSUE TITLE
Support TLSv1.2 in the MQTT operators

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#216]
IBM Watson IoT Platform requires TLSv1.2.

I tried using a system property for the MQTT sink and source

`vmArg: "-Dcom.ibm.jsse2.overrideDefaultProtocol=TLSv12";`

 following this:

http://www.ibm.com/support/knowledgecenter/SSYKE2_7.0.0/com.ibm.java.security.component.71.doc/security-component/jsse2Docs/overrideSSLprotocol.html

but it didn't work.

Adding this into AbstractMqttOperator.java did work:

` sslProperties.setProperty( "com.ibm.ssl.protocol", "TLSv1.2");`

https://www.ibm.com/support/knowledgecenter/SSD28V_8.5.5/com.ibm.websphere.base.doc/ae/rsec_sslclientpropsfile.html

Not sure how this should be exposed as an operator parameter, haven't looked to see if other operators have similar parameter already.

**Comment by ddebrunner** [comment]
I'm going to try the system property with `TLSv1.2` (with the dot) since that value works with the other property.

**Comment by ddebrunner** [comment]
This did not work:
`vmArg: "-Dcom.ibm.jsse2.overrideDefaultProtocol=TLSv1.2";`

**Comment by ddebrunner** [comment]
In the rest operators in streamsx.inet I did this:

```
        sslContextFactory.setIncludeProtocols("TLSv1.2", "TLSv1.1");
        sslContextFactory.setExcludeProtocols("SSLv3");
```

Doing something like this would avoid the need for parameters to the operators.

https://github.com/IBMStreams/streamsx.inet/blob/master/com.ibm.streamsx.inet/impl/java/src/com/ibm/streamsx/inet/rest/engine/ServletEngine.java#L229

**Comment by alexpogue** [comment]
Streams cloud team is also watching this issue, and I am available to help where I can. What's the next step on this?

**Comment by conglisc** [comment]
I am looking into this issue, trying to provide a fix soon.

**Comment by conglisc** [comment]
it looks like the Paho mqtt implementation does not pick up system properties via vmargs.

As @ddebrunner pointed out setting sslProperties.setProperty( "com.ibm.ssl.protocol", "TLSv1.2"); does work. 

I prefer to expose this properties as a parameter of the operator in case users wants to select another ssl protocol, if this parameter is not specified, I will set it to TLSv1.2 as default procotol.

**Comment by conglisc** [comment]
Hi @ddebrunner,

I have merged the code to master, closing this issue now.

**Comment by ddebrunner** [comment]
any idea when a release will be made?

**Comment by conglisc** [comment]
So far I am not aware of any release plans on master branch, can you let me know 

1. Do you must need a messaging toolkit release for IOTF? 
2. If so, when do you need it.

I think it might be a pre-release or special release for IOTF. @chanskw do you agree?

**Comment by ddebrunner** [comment]
If folks want to connect to IBM Watson IoT Platform using encrypted connections then it will be easier for them to download a messaging release rather than having to instruct them to download code and build the toolkit manually.

So the sooner the better, com.ibm.streamsx.iot supports encryption (if the MQTTSource does) and I would like to make it the default before making a 1.0 release.

**Comment by ddebrunner** [comment]
I verified I now now connect to IBM Watson IoT Plaform using SSL.

Thanks!
