### ISSUE TITLE
Moving out of incubation - Need release plan

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#217]
I'd like to try to move the project out of incubation phase.

To do this, we need a clear release plan documented for the project.

Can one of the committers create a release plan for this repository?

Thanks...

**Comment by ddebrunner** [comment]
I'd probably be -1 on graduation due to the lack of tests, I'm not sure the test state in graduation.md is valid.

Issue #212 shows that the tests are being ignored.

And as a contributor I was contemplating making changes over the weekend but the lack of tests made me hesitate, how can any contribute with confidence if they cannot run tests against their changes?

**Comment by chanskw** [comment]
The problem we have here is that our tests are internal..and not open-sourced.

These tests are not maintained.. we should either remove these tests and consider publishing our tests.

**Comment by Alex-Cook4** [comment]
I think we should strongly consider publishing our internal tests rather than trying to update the external tests that currently exist.

**Comment by ddebrunner** [comment]
Looking at the process I see that the testing criteria is "sufficient testing", not that the project itself has tests, so my -1 would probably be invalid.

Though open-sourcing the tests would be a good thing, the current state makes it somewhat hard to contribute.

**Comment by ddebrunner** [comment]
I think issue #211 would need to be resolved before graduation, it's not clear what the versioning scheme currently is, so semantic versioning may not be being followed. 

The release plan may of course clear this up.

**Comment by chanskw** [comment]
I agree.  We do following the versioning scheme.  But adding Kafka, RabbitMQ.. on both 3.2.1 and 4.0.x branch complicates things.  We need do document the project versioning / branching scheme as it's getting very confusing.

**Comment by schulz2** [comment]
While we are still facing the problem of only (mostly?) having internal tests, the toolkit has become part of the product some time ago. Moreover, we already started to deprecate most of it as we have specialized toolkits already. This issue does not make sense anymore ... -> closing ...
