### ISSUE TITLE
Update branching strategy wiki

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#221]
Please update:
https://github.com/IBMStreams/streamsx.messaging/wiki/Project-Branches

**Comment by ddebrunner** [comment]
Any progress on this?

Trying to figure out what to put in a toolkit's info.xml when specifying a dependency on the messaging toolkit.

**Comment by conglisc** [comment]
Still working on it, plan to update in few days.

**Comment by conglisc** [comment]
Hi Dan, 

I have updated project branch page.

**Comment by chanskw** [comment]
Closing.  Please open new issue to discuss if there is any question with the branching strategy.
