### ISSUE TITLE
Add connection related metrics to MQTT operators.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#225]
Would be useful to have metrics related to connection handling, such as number of disconnects, failed/successful attempts etc.

Probably could apply to all the operators, but noticed that the MQTT operators are just a black box when it comes to seeing how stable its connection is.

**Comment by Alex-Cook4** [comment]
+1 This would be helpful. Currently I think these cases are simply logged rather than kept track of.

**Comment by conglisc** [comment]
Hi Dan,

I am trying to understand what kind of connection handling metrics will bring value to user. Do you have any specific needs in knowing things like connection lost, failed/successful attempts.

Thanks,

**Comment by ddebrunner** [comment]
Just an understanding of how stable a connection is.

**Comment by conglisc** [comment]
Hi Dan,

I suggest to add 2 metrics.

1. Number of connection lost
2. Number of successful connection attempts.

Connection lost records number of disconnects and number of successful connection is a counter that is incremented every time when the operator establishes a successful connection to the server. 

These 2 metrics, in my opinion, shows how stable a connection is.

In addition, there is a relationship between these 2 metrics, a healthy MQTT operator instance should show that the successful connection attempts is greater than number of connection lost by 1. A user can get a quick status about MQTT operator.

Thanks,

**Comment by dlaboss** [comment]
The following may go beyond what's needed for a high level assessment of "how stable is the connection" but I'll ask anyway :-)

If I understand the above correctly, those metrics will be unchanging while the operator is iterating attempting to reconnect?  If that's correct, I wonder if a third metric might be helpful in understanding the state of things - something like "Number of current reconnect attempts", incremented for each reconnect attempt, reset to 0 when connected?

I also wonder if any time metrics might be helpful - how long the current connected or disconnected condition has been present?  Essentially a timestamp of when one of the first two metrics was last changed.

**Comment by ddebrunner** [comment]
Another way to put it was my MQTT operators were not connecting the the message hub, but from looking at the instance graph I could not see anything was wrong.

I had to get the logs and then trawl through them to figure out what was going on.

So if the connection is not up to the message hub I would like to know about it easily, e.g. I could have a colour scheme that was red based upon some metrics.

Maybe a gauge that indicates connected 1 disconnected 0

**Comment by conglisc** [comment]
Hi dlaboss, ddebrunner,

I think a gauge is a good choice, which gives instant feedback about status of connection. In addition to that I will add number of connection drops, which gives user some idea about how stable the connection is.

Again, the number of connection drops metric will be reset to 0 for a new mqtt server.

Thank
