### ISSUE TITLE
Branch Clean-up

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#232]
Can one of the committers review all the branches?

Please indicate which of the branches can be removed.

**Comment by chanskw** [comment]
@Alex-Cook4 - please indicate which branch can be removed

**Comment by Alex-Cook4** [comment]
franken and kafka_0.9 branches are safe to remove.

**Comment by conglisc** [comment]
deleted above mentioned 3 branches.

There are few other branches like rabbitmq_3.2.1 and 3 revert branches, anyone know if they are still needed.

**Comment by chanskw** [comment]
Please delete the revert branches.

Please do NOT delete the rabbit mq branch without confirmation from Alex.

**Comment by Alex-Cook4** [comment]
Could we tag rabbitmq_3.2.1 and then delete the branch? That code is still needed and is not located anywhere else. By tagging it, we can create a branch with that code at a later date if necessary.

**Comment by conglisc** [comment]
then we should keep rabbitmq_3.2.1

**Comment by chanskw** [comment]
I agree, we should not delete rabbitmq_3.2.1 in that case.

**Comment by Alex-Cook4** [comment]
sounds good.

**Comment by chanskw** [comment]
please close issue when done  thanks!
