### ISSUE TITLE
RELEASE PROPOSAL:  time for a new release that includes Kafka 0.9 support ?

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/streamsx.messaging#238]
I've been testing the Kafka 0.9 support in the alpha package for a couple of months, and its solid. Others in my group will need this support soon. Can you make a new release package for them?

**Comment by chanskw** [comment]
Thanks Ed for the feedback.  You are basically looking for an official release of the support, and have us remove the "Alpha" or "Pre-release" tag, right?

**Comment by chanskw** [comment]
And for what version of Streams do you need this release for?

**Comment by ejpring** [comment]
I'm using Streams 4.1.1.0 on RHEL 7.1 and CentOS 7.2 ; I think Mark is using RHEL 7.2 or thereabouts. 

Mark is chasing a possible problem with dependencies in the latest version of the toolkit's master branch. After that's resolved, would it make sense to package the current code as a new release, rather than relabeling one of the older packages?

**Comment by chanskw** [comment]
I am not suggesting that we rename existing release.  I am just trying to understand what you are looking for.

So, you want a release from master branch, supporting Streams 4.1.1.0 and Kafka 0.9.  Correct?

If you have defects that need to be addressed for a particular release, and is not resolved yet.  Please add a note to those defects, so we can take a look.  Thanks!

**Comment by ejpring** [comment]
OK, I misunderstood.

I'll let you know when the dependency mystery is solved...

**Comment by chanskw** [comment]
@ddebrunner Can I confirm with you that you are also looking for a release from the master, right?

**Comment by ddebrunner** [comment]
@chanskw Yes, a release that works with Streams 4.1 and has the TLSv1.2 support for MQTT operators.

**Comment by chanskw** [comment]
I am working on this.  Will let you know when I have this ready.

**Comment by chanskw** [comment]
@Alex-Cook4 I am making a release from Master, is there any pending changes in the Kafka operators before a release should be made?  Any fixes I should wait for?

**Comment by chanskw** [comment]
v5.0.0 is released
https://github.com/IBMStreams/streamsx.messaging/releases/tag/v5.0.0
