### ISSUE TITLE
Streams work with Kafka error: Specified output attribute key is not available

### ISSUE THREAD

**Issue by SamDudu** [IBMStreams/streamsx.messaging#239]
Dears,We have came across below error when we launch a SPL program in distributed mode. Any good ideas or suggestions ? Expecting your reply. Thanks

# Version
OS: Redhat linux 6.4 on X86-64
Streams Version: V4.1.1.0
com.ibm.streamsx.messaging toolkit version: 3.0
Kafka Version: 0.8.1
zookeeper version : 3.4.6

# below is the error information:

Last login: Tue May 24 17:27:52 2016 from 10.19.206.221
InfoSphere Streams environment variables have been set.
[streamsadmin@c5streams1 ~]$ export STREAMS_INSTALL=/opt/ibm/InfoSphere_Streams/4.1.1.0;
[streamsadmin@c5streams1 ~]$ /opt/ibm/InfoSphere_Streams/4.1.1.0/java/bin/java -jar /home/streamsadmin/workspace/provRoam/output/com.asiainfo.LTESignal/Standalone/c
om.asiainfo.LTESignal.sab -c -t 1
/home/streamsadmin/workspace/provRoam24 May 2016 17:30:39.737 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0] M[SimpleConsumerClient.java:com.ibm.streamsx.mess
aging.kafka.SimpleConsumerClient.getIntegerProperty:210]  - Property socket.timeout.ms has a final value of 30000
24 May 2016 17:30:39.738 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0] M[SimpleConsumerClient.java:com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.getI
ntegerProperty:210]  - Property simpleConsumer.bufferSize.bytes has a final value of 65536
24 May 2016 17:30:39.738 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0] M[SimpleConsumerClient.java:com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.getI
ntegerProperty:210]  - Property simpleConsumer.fetchSize.bytes has a final value of 102400
24 May 2016 17:30:39.739 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0] M[SimpleConsumerClient.java:com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.getI
ntegerProperty:210]  - Property zookeeper.session.timeout.ms has a final value of 400
24 May 2016 17:30:39.739 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0] M[SimpleConsumerClient.java:com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.getI
ntegerProperty:210]  - Property zookeeper.sync.time.ms has a final value of 200
24 May 2016 17:30:40.003 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.allPortsReady:-1]  - Sp
ecified output attribute key is not available.
24 May 2016 17:30:40.003 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_javaop M[?:?:0]  - java.lang.Exception: **_Specified output attribute key is not avai
lable._**
24 May 2016 17:30:40.004 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_javaop M[?:?:0]  - com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.initializ
e(SimpleConsumerClient.java:296)
24 May 2016 17:30:40.004 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_javaop M[?:?:0]  - com.ibm.streamsx.messaging.kafka.KafkaSource.allPortsReady(Kafk
aSource.java:132)
24 May 2016 17:30:40.004 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.a
llPortsReady(OperatorAdapter.java:789)
24 May 2016 17:30:40.004 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.jni.JNIBridge.allPortsReady(J
NIBridge.java:626)
Exception in thread "Thread-633" java.lang.Exception: Specified output attribute key is not available.
        at com.ibm.streamsx.messaging.kafka.SimpleConsumerClient.initialize(SimpleConsumerClient.java:296)
        at com.ibm.streamsx.messaging.kafka.KafkaSource.allPortsReady(KafkaSource.java:132)
        at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.allPortsReady(OperatorAdapter.java:789)
        at com.ibm.streams.operator.internal.jni.JNIBridge.allPortsReady(JNIBridge.java:626)
24 May 2016 17:30:40.006 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_function M[JavaOp.cpp:allPortsReady:1382]  - CDISR5126E: A Java exception occurred
 at Operator.allPortsReady() during the JavaOp invocation.
24 May 2016 17:30:40.008 [32420] ERROR #splapptrc,J[0],P[0],LTE_KafkaStream[0],spl_pe M[PEImpl.cpp:process:860]  - CDISR5079E: An exception occurred during the proce
ssing of the processing element. The error is: A Java exception occurred at Operator.allPortsReady() during the JavaOp invocation..

# Next is the related SPL program:

namespace com.asiainfo ;

use com.ibm.streamsx.messaging.kafka::* ;
type signalObject = rstring eventID, rstring time, rstring lac, rstring ci,
	rstring callingimei, rstring calledimei, rstring callingimsi,
	rstring calledimsi, rstring callingphone, rstring calledphone, rstring stype,
	rstring eventresult, rstring alertstatus, rstring assstatus,
	rstring clearstatus, rstring relstatus, rstring xdrtype, rstring issmsalone,
	rstring lac_sou, rstring ci_sou ;
type time_type = tuple<int32 sec, int32 min, int32 hour, int32 mday, int32 mon,
	int32 year, int32 wday, int32 yday, int32 isdst, int32 gmtoff, rstring zone> ;

	/**
 * 
 * LTE MC 
 */
composite Comp3(input LTE_KafkaStream )
{
	graph
		stream<rstring topic, rstring message> KafkaOut = Custom(LTE_KafkaStream)
		{
			logic
				state :
				{
					mutable list<rstring> line ;
					mutable timestamp ts2 ;
					mutable time_type tp2 ;
				}

				onTuple LTE_KafkaStream :
				{
					line = tokenize(LTE_KafkaStream.message, "|", true) ;
					//time((timestamp)line[9],tp2) ;
					//time(fromDecimal128((decimal128) line [ 9 ] *(decimal128) 1000000), tp2) ;
					time(fromDecimal128((decimal128) line [ 9 ] ), tp2) ;
					//rstring t2_prefix = strftime(tp2, "%Y-%m-%d %H:%M:%S") ;
					submit({ topic = "topic_mc_lte_out", message = line [ 8 ] + "," +
						strftime(tp2, "%Y-%m-%d %H:%M:%S") + "," + line [ 32 ] + "," + line [ 33
						] + "," + line [ 6 ] + "," + "000000000000000" + "," + line [ 5 ] + "," +
						"000000000000000" + "," + substring(line [ 7 ], 0, 11) + "," +
						"00000000000" + "," + "0" + "," + "0" + "," + "0" + "," + "0" + "," + "0"
						+ "," + "0" + "," + "0" + "," + '0' + "," + '0' + "," + '4g' },
						KafkaOut) ;
				}

				//config placement: partitionColocation("AB");

		}

		() as KafkaSink = KafkaProducer(KafkaOut)
		{
			param
				propertiesFile : "etc/producer.properties" ;
				//config placement: partitionColocation("AB");
				vmArg : "-Xmx1024m" ;
		}

}

composite LTESignal
{
	graph
		@parallel(width = 300)
		stream<rstring message> LTE_KafkaStream = KafkaConsumer()
		{
			param
				propertiesFile : "etc/consumer.properties" ;
				topic : "topic_lte_s1_mme" ;
				partition : getChannel() ;
				vmArg : "-Xmx1024m" ;
				//keyAttribute : "key" ;
			config
				placement : partitionColocation("AB") ;
		}

		@parallel(width = 10)
		() as out = Comp3(LTE_KafkaStream)
		{
			config
				placement : partitionColocation("AB") ;
		}

		//config
		//placement : host("c4streams15") ;

}

Thanks a lot

**Comment by Alex-Cook4** [comment]
This is a bug where the key is a required attribute in the output stream from the Kafka Consumer. You need to modify the LTE_KafkaStream to have a key attribute:

`type LTE_KafkaStream = tuple\<rstring message, rstring key>;`

**Comment by Alex-Cook4** [comment]
Fixed in the latest 5.0 release.
