### ISSUE TITLE
Revert toolkit version from v5.2.0 to v5.0.0

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#240]
Looking at the messaging toolkit, the toolkit version was somehow bumped to v5.2.0.  Since we have not done any release with this toolkit, this bump was not necessary.  Moving it back to 5.0.

**Comment by Alex-Cook4** [comment]
Doesn't this go against the discussion in #207? That we should be bumping versions when features are added? One of the features was URI support for RabbitMQ (cloud enablement)...not positive what the other one was.

**Comment by chanskw** [comment]
Version number bumps happens when we release the toolkit.
Since we have never done a 5.0 release, it does not make sense to bump the version number.

**Comment by Alex-Cook4** [comment]
Ok, thanks for clarifying!

**Comment by chanskw** [comment]
Fixed
