### ISSUE TITLE
Upgrade to Kafka 0.10.0.0

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#244]
We recently upgraded to the stable Kafka 0.9.0.1 release. Since Kafka recently released version 0.10.0.0 I am opening this issue to track our move to that. 

I ran a quick test and I wasn't able to get the 0.10 client to immediately work with my 0.9.0.1 servers. I will be looking deeper into this as I believe our clients should be backwards compatible with 0.9 servers.

**Comment by Alex-Cook4** [comment]
Upon further digging, moving to Kafka 0.10 will break support for 0.9 clients. I still think we should move to 0.10 to stay in sync with Kafka. 

What do others think? Do we want to up the version number again since this will be a breaking change?

**Comment by Alex-Cook4** [comment]
I would like to hold off on doing this until #246 is resolved.

**Comment by Alex-Cook4** [comment]
I plan to move forward with this since Message Hub has moved to Kafka 0.10 and moving our clients to that will simplify integration.

**Comment by ddebrunner** [comment]
Is there any way to make this a non-breaking change? Just has an effect on other apps/toolkits that depend on this toolkit that don't use kafka so effectively the new version is compatible.

For example, can a parameter be added to the Kafka operators to indicate which client version they use?

It just seems that it will become a maintenance nightmare if a new version and new branch has to be created every time a new kafka client is used. E.g. having to backport non-kafka fixes across multiple versions of the toolkit.

**Comment by Alex-Cook4** [comment]
That's the main motivation behind #246...it is already becoming a nightmare. 

One possibility is to have different ant targets: 

ant kafka9
ant kafka10

I'm a little hesitant to start expecting these changes to be non-breaking...Kafka has put out a breaking client for every major release (2 in the last 8 months). Once we break out Kafka from the messaging toolkit, this shouldn't be an issue.

**Comment by Alex-Cook4** [comment]
Removing must-fix tag as I think we can wait a little longer...we have had no requests for this yet. Once we do incorporate, we will have the build option for different targets.

**Comment by Alex-Cook4** [comment]
This was handled in the 5.1 release.
