### ISSUE TITLE
reconnection of kafkaconsumer

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.messaging#253]
Hi     I found a problem that kafkaconsumer lost connection to kafka server after running well for some time.  There are no errors in streams log and in kafka log.  after restart the job, the connection will be built again. 
 is there any mechanism to know if the connection is lost and to reconnect to kafa? 

kafka server version: 0.8
kafka toolkit version 2.01

**Comment by chanskw** [comment]
This is already handled by the Kafka client out of the box.
