### ISSUE TITLE
Need information on how to setup Kafka operators.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#257]
A `com.ibm.streamsx.messaging.kafka/namespace-info.spl` file with overall kafka documentation would be useful describing what properties are required/used in the properties file. The only doc I could see was the parameter comment saying the properties files contains Kafka properties. 

I looked in the samples and see both the producer and consumer have:
` bootstrap.servers=broker.host.1:2181,broker.host.2:2181,broker.host.3:2181`

While you have to put your own server addresses there, the sample looks like it's pointing to the Zookeeper instance rather than the brokers, is that correct? E.g. should port 9092 be used as the example?

I'm followed this to set up my Kafka server:
http://czcodezone.blogspot.com/2014/11/setup-kafka-in-cluster.html

and the producer example takes a broker list, while strangely the consumer takes the zookeeper list.

**Comment by ddebrunner** [comment]
I just found this:
http://ibmstreams.github.io/streamsx.documentation//docs/4.1/messaging/kafka-operators-getting-started/

which does have servers `bootstrap.servers` pointing to the brokers (9092), not the traditional ZK port.

**Comment by Alex-Cook4** [comment]
Thanks for bringing this up. What about pointing to the Kafka properties in the SPLDOC? https://kafka.apache.org/documentation.html#producerconfigs and https://kafka.apache.org/documentation.html#newconsumerapi 

The broker ports should all have 9092 as the port since they point to Kafka Brokers since 0.9.

**Comment by ddebrunner** [comment]
Pointing to the kafka doc from the namespace-info would be a help, but also stating what;s the minimal set of required properties would be helpful.

**Comment by Alex-Cook4** [comment]
@ddebrunner I have updated the SPLDOC to include information about properties. You can see it here: http://ibmstreams.github.io/streamsx.messaging/com.ibm.streamsx.messaging/doc/spldoc/html/index.html
