### ISSUE TITLE
XMS operator requires document update to change the way env variables are configured

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#259]
XMS operator requires LD_LIBRARY_PATH env variable, but in OLETA, this should be specified vi streamtool setproperty --zkconnect d0110b10:2183 -d cong42 -i cong42 --application-ev LD_LIBRARY_PATH=/opt/IBM/XMS/lib/4.1:/opt/IBM/XMS/lib64/4.1:/opt/IBM/XMS/lib64/:/opt/IBM/XMS/lib:/opt/mqm/lib64:/opt/mqm/lib

Need to update document for XMS to inform users of this change

**Comment by schubon** [comment]
We do not know of any customer using the XMS part of this toolkit. All other parts have been made into their own toolkits.
