### ISSUE TITLE
Question: Information on how Kafka operators handle message types?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#260]
I couldn't see anything in the SPLDOC about how the Kafka operators handle data types.

Since a Kafka message is just bytes, it seems (from #112 ) that if the message attribute is rstring then the bytes are assumed to be UTF-8 and converted into an rstring, which is natural.

But what about if the message is binary data, can I have the message attribute be `blob message` ?

**Comment by ddebrunner** [comment]
From this line:
https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/kafka/AttributeHelper.java#L60

it seems there is code to support blob attributes, when the attribute is not rstring or ustring.

**Comment by Alex-Cook4** [comment]
Sorry @ddebrunner, I thought I responded to this. We support rstring, ustring, and blob attributes for the message and key. I will add this to the SPLDOC.

**Comment by ddebrunner** [comment]
Thanks @Alex-Cook4 , I got KakfaProducer and Consumer working with blob messages!

**Comment by Alex-Cook4** [comment]
Added this to the SPLDOC: http://ibmstreams.github.io/streamsx.messaging/com.ibm.streamsx.messaging/doc/spldoc/html/index.html
