### ISSUE TITLE
Optimize Kafka AttributeHelper

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#261]
- AttributeHelper must be invoked frequently, once per message/tuple but has all these checks about if it is available or a string. Since these are known at initialization time it would be more efficient to have a String version and a Bytes version(*) rather than check every tuple. Not sure if a NotAvailable version is needed, since if the attribute is not available an exception is thrown, so unclear why it needs to be checked on every access.
- If converting from `byte[]` to an `rstring` it would be more efficient to use `RString` than go through String.
- When going from a Blob to byte[] the bytes are copied from the Blob. I'm wondering if this copy could be avoided by having the Blob passed closer to the Kafka api.
- Since the attribute's name is known, initialization code could get the attribute index and use that for the tuple getters/setters to avoid a name to index translation on every tuple/message.

(*) There may be a case to say this code should be in the type specific (Byte/String) consumers rather than needing an AttributeHelper class.

**Comment by Alex-Cook4** [comment]
Thanks for the input @ddebrunner! When I get some time to look into these, I will follow-up with questions/what changes I have made.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
