### ISSUE TITLE
KafkaConsumer threadsPerTopic parameter?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#265]
In version 3.0 of the toolkit KafkaConsumer supported a threadsPerTopic parameter, but it no longer exists in version 5 of the toolkit. 

Is there any guidance related to this, what to do applications that previously set it?

TIA

**Comment by Alex-Cook4** [comment]
@ddebrunner, the new KafkaConsumer Client that was released with Kafka 0.9, is single-threaded. Therefore the threadsPerTopic parameter is obsolete and was removed. 

Are you suggesting that we have a "Removed parameters" section to explain this?

**Comment by ddebrunner** [comment]
Not sure, but some documentation somewhere would have been useful.

Another approach for backwards compatibility would have been to keep the parameter (and ignore it) and document it as deprecated.

**Comment by Alex-Cook4** [comment]
@ddebrunner In the future I will be more careful about deprecating rather than deleting :-) 

I have added an explanation to the SPLDOC: http://ibmstreams.github.io/streamsx.messaging/com.ibm.streamsx.messaging/doc/spldoc/html/index.html
