### ISSUE TITLE
Question: 5.1 release only 4.2?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#266]
Looking at the changes in the 5.1 release there doesn't seem to be anything that forces a dependency on Streams 4.2?

Having a toolkit only work with the latest release limits its use, customers are still using the older releases (I'm (indirectly) dealing with a customer that is still on 3.2), adoption of a new release takes time.

Just wondering what the plans are, if a new feature is added that is needed for 4.0/4.1 based upon the 5.0 toolkit, what would the version be?

**Comment by Alex-Cook4** [comment]
The issue we run into with this supporting old releases is that the new version with AppConfig has API's that don't exist with older releases of Streams. 

The reason for not making this a 6.0 release was that from an SPL code perspective, this toolkit is completely backwards compatible. So an application written with an earlier version of the toolkit can upgrade seamlessly. 

As for actually answering your question...I think that will pose a challenge. Any proposals? We could do a 5.0.x release, even though that's supposed to be for bug fixes.

**Comment by ddebrunner** [comment]
I couldn't see any changes related to the application config apis in 5.1 though?

https://github.com/IBMStreams/streamsx.messaging/compare/5.0.1...5.1.0

**Comment by Alex-Cook4** [comment]
@ddebrunner We fixed the release today so that it actually has the AppConfig from our internal development. Thanks!
