### ISSUE TITLE
KafkaProducer doesn't state how it behaves in a consistent region.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#267]
The SPLDOC for `KafkaProducer` just states it can be used in a consistent region, but not how it behaves. Will another consumer of the topic see a message from streams exactly once or at least once?

**Comment by Alex-Cook4** [comment]
New doc should address this: http://ibmstreams.github.io/streamsx.messaging/com.ibm.streamsx.messaging/doc/spldoc/html/index.html

Thanks!
