### ISSUE TITLE
Fused KafkaConsumer & KafkaProducer not working.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#279]
I have a simple SPL app that has a `Beacon` with a period of 0.5 (two a second) feeding a `KafkaProducer` and a `KafkaConsumer` reading the same topic.  They have different client identifiers. The Kakfka broker is MessageHub on Bluemix.

With Streams 4.2 the two Kafka operators end up on the same PE and tuple/messages fail to flow successfully. It seems to be a message sent from the producer every minute and the consumer sees nothing.

Forcing the two Kafka operators to be on separate PEs makes everything work normally.

**Comment by ddebrunner** [comment]
Complete App: (see #278 for details on connecting to message hub).
```
namespace example.kafka ;

use com.ibm.streamsx.messaging.kafka::KafkaConsumer ;
use com.ibm.streamsx.messaging.kafka::KafkaProducer ;

boolean startup() {
println("getThisToolkitDir():" + getThisToolkitDir());
return false;
}

composite Main
{
	graph
		stream<rstring key, rstring message> B = Beacon()
		{
		logic state: boolean s = startup();
 		param
				period : 0.5 ;
		output B:
				key = "K" + (rstring) ((int32) IterationCount() % 100),
				message = "XXXXXXXXXXXXXXX" + (rstring) IterationCount();
		}
		
		() as KafkaProducer_2 = KafkaProducer(B)
		{
		param
		topic: "sms";
		
		appConfigName: "debrunne-message-hub";
		appConfigPropertyName: "bootstrap.servers";
		
		kafkaProperty:
		    "client.id=Dan001",
		    "acks=0",
            "security.protocol=SASL_SSL",
            "ssl.protocol=TLSv1.2",
            "ssl.enabled.protocols=TLSv1.2",
            "ssl.truststore.type=JKS",
            "ssl.endpoint.identification.algorithm=HTTPS";
            
        jaasFile: getThisToolkitDir() + "/etc/jaas.conf";
        // config placement: partitionExlocation("A");
        
		}
		
		stream<rstring key, rstring topic, rstring message> KC = KafkaConsumer() {
		param
				appConfigName: "debrunne-message-hub";
		appConfigPropertyName: "bootstrap.servers";
		topic: "sms";
		
		kafkaProperty:
		    "group.id=Dan",
		    "client.id=Dan002",
            "security.protocol=SASL_SSL",
            "ssl.protocol=TLSv1.2",
            "ssl.enabled.protocols=TLSv1.2",
            "ssl.truststore.type=JKS",
            "ssl.endpoint.identification.algorithm=HTTPS";
            
        jaasFile: getThisToolkitDir() + "/etc/jaas.conf";
		//config placement: partitionExlocation("A");
		}
		
		stream<KC>KC2 = Functor(KC) {}
}
```

**Comment by ddebrunner** [comment]
The fact that the JAAS configuration is setting a system property seems a potential area for concern.

If there are multiple operators talking to different Kafka instances then they will overwrite each other's config if fused. Ideally the operator would not use a system property to create an operator specific configuration, no idea if that's possible with JAAS.

I don't see anything in the docs about requiring these operators to run on different PEs.

**Comment by leongor** [comment]
The issue became more critical because of Streams 4.2 new fusion schema.
Suggest to rise the priority of the issue.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
