### ISSUE TITLE
Support for Apache Rabbit MQ?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#28]
Source and sink operators for supporting Apache Rabbit MQ:
https://www.rabbitmq.com/

**Comment by Alex-Cook4** [comment]
@saidmohamedali Have you had a chance to sign and send @petenicholls this form: https://github.com/IBMStreams/administration/blob/master/IBMStreams-cla-individual.pdf ? There has been some interest in your code and we would love to try to incorporate it!

**Comment by Alex-Cook4** [comment]
Thank you for the contribution from @saidmohamedali. We support RabbitMQ now.
