### ISSUE TITLE
Provide simple integration with MessageHub.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#280]
It would be good to have easier setup for integration with MessageHub, for example:

* Composites that wrapped `KafkaProducer` and `KafkaConsumer` setting all required parameters (e.g. ssl settings) and pulled all connection from an application configuration (4.2 only). See #278 
* Micro-service that read from a topic and republished it as a Streams topic using `Publish`.

**Comment by Alex-Cook4** [comment]
+1 I think this would be a great enhancement. 

I think the main barrier to making this happen is setting the jaas.conf as a system property, and having the Message Hub credentials in there. Assuming we can resolve that, this should be very doable and helpful.

**Comment by leongor** [comment]
+1

**Comment by ZollnaPa** [comment]
+1 I guess, the application configuration is the right solution for all the configuration properies, special for passwords.

**Comment by ZollnaPa** [comment]
wrong button...

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
