### ISSUE TITLE
Allow JAAS password to come from application configuration.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#281]
See #278.

**Comment by natashadsilva** [comment]
+1.  This is needed not only for Bluemix but now with DSX support, there is no (easy?) way to upload the jaas config file to a notebook.  
So right now I'm using a generic Python Kafka client but it's much better to rely on the operators (consistent regions being one reason)

So can we please add this as an enhancement?

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
