### ISSUE TITLE
Remove requirement that the key and message type match.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#282]
A common case is a string key and a blob message, forcing the SPL developer to use the same type seems unreasonable. The operator could covert the keys to matching types internally.

**Comment by Alex-Cook4** [comment]
This should be pretty easy to do. 

From the consumer side: 
We just need to add a KafkaStringKeyByteArrayMessageConsumer and we might as well ad a KafkaByteArayKeyStringMessageConsumer while we're at it. Similar to this: https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/kafka/KafkaByteArrayConsumerV9.java

From the producer side: 
Similar changes to https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/kafka/KafkaProducerClient.java to add the support. May be worth thinking about how to refactor this...

Last step would be to remove any type checking.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
