### ISSUE TITLE
KafkaConsumer doesn't enforce checkpointing rules outside of the consistent region

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#288]
We do some checks to make sure that the consistent region is only done in a single-topic, partition specified configuration, but we don't enforce those rules if checkpointing is enabled. 

In the KafkaSource, we should check consistent region context, as well as CheckpointContext.

**Comment by ddebrunner** [comment]
Why would we need the same checks for regular checkpoint? Couldn't we just checkpoint the offsets for each {topic,partition} pair? Maybe initially it could be limited to a single topic and partition, but in the future that could be relaxed, even in a consistent region.

The checkpoint code is confusing as its coded as if it does support multiple topics and partitions, but actually doesn't handle it correctly. E.g. why is a `Map<Integer,Long>`  used as the stored object if it only supports a single partition, so it only needs to store a single `Long`.

**Comment by Alex-Cook4** [comment]
The checkpoint code supports multiple partitions for only a single topic. So our current check ensures the single topic, and that the desired partitions are specified. 

Why would we do anything different for regular checkpoint verses consistent region? 

For relaxation in the future (in order): 
1.  Allow multiple topics/partitions -- the struggle with this has been, how should users provide topics AND partitions, since partition and topic parameters are separate? 
2. Allow only topic to be provided, then use Kafka API's to get partition information. 

I think what we want to actually be saving in the future is what we get from consumer.assignment()...maybe it will be straightforward? (https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/kafka/KafkaConsumerClient.java#L114):
`Set<TopicPartition>` partitionSet = consumer.assignment();

We will have to cast it to an object whenever interacting with the checkpointing APIs as they do not support Kafka types (I think I played with this at one point and ran into issues with the types).

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
