### ISSUE TITLE
Proposal: Allow KafkaConsumer to load its initial offsets from an external location.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#291]
Provide a mechanism where the offsets for a topic in a consistent region can be saved to and loaded from an external store. This would allow hand over from one Streams application to another, e.g. a replacing an application with a newer version while maintaining processing of all records.

Concept is to:
a) Allow an optional output port. On checkpoint the current offset map are saved in memory, corresponding to the end of the current cut. When the callback `regionCheckpointed` is called the saved offset map is converted to a tuple and submitted, so a downstream operator within the region can then write it into a persistent store.

b) Allow an optional control input port.  On startup wait for a tuple in the input that contains the starting offsets. Need to have details on the protocol here.

Required schema for the optional ports would be the standard JSON `rstring jsonString`. This allows for flexibility in what could be submitted to the "control" output port.

I'm experimenting with this to see how feasible it is.

Potentially a composite operator could be provided that would be a drop in replacement for the existing KafkaConsumer, but supported the external offset storage in Zookeeper.

[updated to send tuple when region is checkpointed, not the source operator drained]

**Comment by Alex-Cook4** [comment]
It sounds feasible and useful for a production environment. A couple of thoughts came to mind: 

1. Would we want a way to send a "stop" signal after they had sent the offsets to the persistent store? Effectively "draining" this application, then starting the new one. This could help keep an exactly-once processing for the application (even though sinks tend to have an at-least-once constraint, the fewer repeats, the better). 
2. Would we want to handle an offset not existing any differently than we normally do? Normally we would just go by the auto.offset.reset parameter. We can recommend though that people who require it to work exactly as expected would want auto.offset.reset=none, which should throw an exception.

**Comment by ddebrunner** [comment]
I have this working to some extent, using a composite with a `LeadershipElection` operator and writing and reading the latest offsets from Zookeeper using `ZnodeAction` operators.  The leadership election allows the second application to take over immediately once the other application is stopped or canceled. 

The offsets for a completed region are continually updated in Zookeeper, so that any application can take over at any time. It also allows stopping an application and restarting it later at the same point.

For a clean handover we do need a mechanism to stop the `KafkaConsumer` reading messages and wait for the final region to be completely checkpointed. But in some scenarios it can work without this.

I'm cleaning up the code to provide incremental pull requests, rather than one big request. The metrics one (pr #294) was a first step.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
