### ISSUE TITLE
KafkaConsumer performs debug tracing at level INFO.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#292]
`KafkaSource.java` has much debug style tracing at level INFO, e.g. every call to the state handler.
Trace at INFO level is suitable for initialization stuff, like the list of topics, but to have it on every state handler call seems excessive.

Customers have complained in the past about excessive tracing.

I would propose to change this to be DEBUG level tracing.

**Comment by Alex-Cook4** [comment]
+1

**Comment by natashadsilva** [comment]
+1

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
