### ISSUE TITLE
Change Kafka Consistent Region sample to use recommended property

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#296]
https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html recommends setting `enable.auto.commit=false` when manually storing offsets. 

We could potentially force this property to be set like this in the case of ConsistentRegion, but I worry there might be cases where users would want to have control. For example, if autocommit is enabled, they can see offset consumption from the Kafka command line.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
