### ISSUE TITLE
MQTT operator support for MQTT 3.1.1 Spec

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#3]
Investigate support of MQTT 3.1.1 with MQTT operators
MQTT 3.1.1 provides support for failover and HA, where we can pass in a list of servers to the client.  The client will attempt the reconnect and automatically try other servers on the list when a connection is lost.

**Comment by schubon** [comment]
Customers are already using the new toolkit https://github.com/IBMStreams/streamsx.mqtt
