### ISSUE TITLE
Nominate @cancilla as committer to streamsx.messaging

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#300]
I'd like to nominate @cancilla to be a committer to the streamsx.messaging project.

James has contributed the SSL support for JMS operator to the messaging toolkit.  James has made many significant contributions to the IBMStreams community and his work is always of excellent quality, that shows deep expertise to IBM Streams and the technologies that he is working with.

**Comment by ZollnaPa** [comment]
The product responsibility has @schulz2, He has to be 'main' committer to the streamsx.messaging project..

**Comment by mikespicer** [comment]
+1 to @cancilla being a committer
@ZollnaPa There can be many committers based on contributions, I don't believe we need to have a "main" committer, all committers have the same authority and associated responsibility.

**Comment by chanskw** [comment]
Thank you all!  Added James as committer.

Welcome James!
