### ISSUE TITLE
NLS Work Review and Suggestions

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#302]
* Is it possible to collect all message files to a single resource folder, rather than having it distributed as part of the source tree?  It makes the source tree messy, and also hard to manage the resource files.  

* In addition, when I look at the *.xlf files, there are internal copyrights that should be replaced by open-source project copyrights.

* In my understanding, the *.xlf files generate the *.properties files?  What is the process of building the *.properties file, if any?  Can I still create a messaging toolkit release, with the right properties files ?  Can you please document the process?

**Comment by ZollnaPa** [comment]
- The movement of the resource files is not comfortable. The translation team use tooling that checks for differences. If the file is moved then the translation must be processed from scratch for the next update.  

- The properties file are implemented by hand for java code. The *.xlf file is used for the generation of a binary *.dat file, that provides the messages for C++ and PERL code. The additional include folder is created that includes the header file and the PERL module. The spl-make-toolkits generates the include folder content. The XLF file entry must exit in the info.xml of the toolkit.
The Localization sample is a good example for the XLF file handling.

**Comment by schulz2** [comment]
In a previous discussion I already explained, that the XLF and Java properties files reside with the respective operators for the different message queues as the messaging toolkit will probably be split into single toolkits per message queue. So I will not merge it into one file.

I will look into the copyright issues in the next week.

**Comment by chanskw** [comment]
Thanks for the explanation.  It would be nice if the process and design is documented somewhere.  For example, if someone from the community is trying to add new messages for Java / C++, what process or guideline one should follow to make sure that translation is not broken?

**Comment by ZollnaPa** [comment]
Yes, is created the following issue to keep it in mind:
https://github.com/IBMStreams/administration/issues/105
