### ISSUE TITLE
MessageHub sample and documentation need update

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#306]
The KafkaSASLSample and its instructions here is out of date:

https://www.ibm.com/blogs/bluemix/2015/10/streaming-analytics-message-hub-2/

I think we need to update the documentation and sample ASAP, as connecting to MessageHub does not work out of the box.

**Comment by chanskw** [comment]
@alexpogue I opened this work item.

**Comment by alexpogue** [comment]
The likely scope of changes can be seen in alexpogue/streamsx.messaging#1. I will test these changes today and make a PR to IBMStreams/streamsx.messaging

**Comment by alexpogue** [comment]
I made #307 to fix this. Merge when ready

**Comment by chanskw** [comment]
Fixed.  Thanks @alexpogue
