### ISSUE TITLE
Allow for integer keys in Kafka Consumer/Producer

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#308]
Kafka offers serialization and deserialization in types other than String and ByteBuffer. I think we should consider adding support for an integer key, since an "integer id" is a case we have run into for a key. 

Here are the available serializers: https://kafka.apache.org/0100/javadoc/org/apache/kafka/common/serialization/package-frame.html

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
