### ISSUE TITLE
Doc: JMS operators don't explain whether they support at-least-once or exactly-once

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.messaging#314]
JMS operators don't explain whether they support at-least-once or exactly-once

**Comment by Alex-Cook4** [comment]
It is also not clear what happens in the case of a reset to initial state.

**Comment by dakshiagrawal** [comment]
Well - an operator would support exactly one or at-least once depending on the rest of the application. What is not clear from the documentation is behavior (or timing relationships) of a transaction commit and checkpointing activity.

**Comment by Alex-Cook4** [comment]
@dakshiagrawal yes, that was me being a bit slow :-) I'll close this issue and focus the questioning in #315
