### ISSUE TITLE
Deprecate Kafka operators

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.messaging#316]
The Kafka operators in the `com.ibm.streamsx.messaging` toolkit have been replaced with the operators in the `com.ibm.streamsx.kafka` toolkit. The operators in this toolkit need to be deprecated. 

#### Deprecation Actions
 - [x] Add compile-time warning indicating that the operators have been deprecated
 - [x] Log a message at runtime indicating that the operators have been deprecated
 - [x] Replace the operator icons with greyed-out icons containing a red slash to indicate deprecation
 - [x] Add a message to the operator's SPLDoc to indicate that it has been deprecated
 - [X] Create migration guide for moving to the new toolkit ([HERE](https://github.com/IBMStreams/streamsx.kafka/wiki/Migration-Document-(Messaging-Toolkit-to-Kafka-Toolkit)))

**Comment by Alex-Cook4** [comment]
+1

**Comment by ddebrunner** [comment]
>  Replace the operator icons with greyed-out icons containing a red slash to indicate deprecation

That's a nice idea.

**Comment by ZollnaPa** [comment]
+1 with remarks:
1. Are the restrictions described, if any exists? 
2. I would expect the information about the compatibility of kafka versions supported by the old operators in messaging toolkit and by the new kafka toolkit. You could add 1-2 sentences in your migration guide.

**Comment by schulz2** [comment]
Changes added to v5.3.2
