### ISSUE TITLE
JMSSource doesn't reconnect after server restart or connection loss

### ISSUE THREAD

**Issue by rnostream** [IBMStreams/streamsx.messaging#319]
In case the server crashes and restart or just network connection was loss the JMSSource doesn't reconnect.

Behavior is already analyzed, both scenarios will lead to a TCP connection loss. This is detected by AMQ client lib but not by JMSSource operator code because of the fact that the connection loss exception is an ansynchronous event not being catch by operator try/catch block. An ExceptionListener method has to be registered to the connection to be informed. If such event occurs the connection used in operator has to be closed and reopened according the reconnection parameters provided to the operator.

**Workaround is available:**
AMQ client lib is able to cover these scenarios by [AMQ transport failover feature]( http://activemq.apache.org/failover-transport-reference.html). You can enable this by putting ` provider_url = "failover:(tcp://1.2.3.4:61616)"` to the connection specification (in connection.xml) used by the JMSSource. So the AMQ client lib will try an failover (to the only one url which exists) when TCP connection loss is detected. Nevertheless the JMSSource operator as well as the whole SPL application will not be informed with this workaround, even if there is never a successful failover.

**Comment by schulz2** [comment]
Changes added to v5.3.3
