### ISSUE TITLE
Nats.io support request

### ISSUE THREAD

**Issue by nicknezis** [IBMStreams/streamsx.messaging#330]
Would be nice to have a Nats.io Source and Sink. There are native libraries and Java. http://nats.io/download/nats-io/jnats/

**Comment by chanskw** [comment]
Thanks for the suggestion!  We will take a look at it.

**Comment by schulz2** [comment]
Hi @chanskw ,
given that we are splitting streamsx.messaging into smaller toolkits like streamsx.kafka and streamsx.rabbitmq, shouldn't we - if we decide so - create an own toolkit streamsx.nats instead of augmenting streamsx.messaging?

**Comment by chanskw** [comment]
Yes.. I agree this is a good suggestion.  However, we can only create a repository if there is code contribution for this support.  Is there a prototype for this already?

**Comment by schulz2** [comment]
Not from my side. Having fun with other stuff :-)

**Comment by schubon** [comment]
The requested functionality will not be added to the Messaging toolkit anymore. Please, check if https://github.com/IBMStreams/streamsx.nats fulfills your needs.
