### ISSUE TITLE
CDISP9211E ERROR: The MessagingResource.xlf xliff file was not converted. CDISP0786E ERROR: The generation of the MessagingResource resource bucket failed.

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.messaging#331]
when ant kafka-0.9 , there is following error. I have no idea how to resolve. please help.
CDISP9211E ERROR: The MessagingResource.xlf xliff file was not converted.
CDISP0786E ERROR: The generation of the MessagingResource resource bucket failed.

**Comment by schulz2** [comment]
Hi sunruns,

I tried to reproduce even by downloading the streamsx.messaging-5.3.1 source package under releases, but on my machine it runs (I even forcefully deleted xlf compile result files in trying to provoke the error). The big difference though between your and my build log is, that I have a block where dependencies are copied from Maven. Additionally, in your log I see:
...
toolkit:
[echo] Tookit to index: /home/streamsadmin/streamsx.messaging-5.3.1/com.ibm.streamsx.messaging
[exec] CDISP9211E ERROR: The MessagingResource.xlf xliff file was not converted.
[exec] CDISP0786E ERROR: The generation of the MessagingResource resource bucket failed.
[exec] Result: 1
Caught an exception while logging the end of the build. Exception was:
java.lang.NoSuchMethodError: com/ibm/icu/impl/ICUBinary.getData(Ljava/lang/ClassLoader;Ljava/lang/String;Ljava/lang/String;)Ljava/nio/ByteBuffer;
...

Checking for ICUBinary shows JARs that belong to the Maven distribution.

This leads to the question:
**Do you have Maven installed on your machine?**

Kind regards
Norbert

**Comment by sunruns** [comment]
Hi Norbert,
     thanks for you help.
     In my quick start vm, there is internet connection. so ant kafka-0.9 or all or clean is okay.
     then I copied the jars in the opt/downloaded directory to a linux node which can't access internet.
there are maven and ant installed in the linux machine, but just can't download the jars from maven repository. 
      there is no ICUBinary jar in those jars which downloaded. so could you please tell me which jar i should download , then i can copy into opt/downloaded.
     as the xiliff part, it should be another problem. for sometimes there is no icu error when ant, but the xlf error always exists.

**Comment by schulz2** [comment]
Hi sunruns,

as I see it ICUBinary is not used within the toolkit but by Maven. So if you have Maven installed it should already be on your machine. I have tested on my development machine and not in a Quickstart Edition (QSE). Couple of questions:
You are using the latest QSE?
Which runs Red Hat 7?
You are using the streamsx.messaging toolkit that has been delivered with QSE (you did not download it from GitHub)?
Then you build and move over to a different machine?
Does your package have the .../impl/nl directory in it and is it filled (with include subDir and MessageResource.dat and Locale directories?

Kind regards
Norbert

**Comment by sunruns** [comment]
Hi Norbert,
   to clarify, all work fine on my vm.
   On the metal machine, it failed. the streams version is 4.0.1.0. the os is redhat 6.5.  I downloaded the streams.messaging  toolkit source code 5.3.1 from github.com. I also installed ant and maven on this test machine. and for the 1st time, ant built successfully. but after I changed the jars in the $STREAMS_INSTALL/java/jre/lib/ext and a different JAVA_HOME, ant built failed with the error. I don't know how to resolve this error.

**Comment by schulz2** [comment]
Hi sunruns,

can you detail this sentence of yours, please:

>>> ... but after I changed the jars in the $STREAMS_INSTALL/java/jre/lib/ext and
>>> a different JAVA_HOME, ant built failed with the error

1) Have you changed back to the original state and rerun the build successfully?
2) What exactly did you exchange?
3) Why?
4) What are the current values/contents of JAVA_HOME and $STREAMS_INSTALL/java/jre/lib/ext ?

Kind regards
Norbert

**Comment by schulz2** [comment]
Hi sunruns, 
there is one thing I missed in your last answer. The part that doesn't compile is in the translation which only has been introduced with streams v4.2.1. Thus the main problem here is, that you are using a Streams installation that is too old.

Kind regards
Norbert

**Comment by sunruns** [comment]
Hi Robert,
     I am testing if this toolkit can produce and consume to Kafka 0.9 broker.
     I have successfully compile this toolkit with ant all in the streams v4.0.1 env, then successfully produce and consume to Kafka 0.10 broker. In the very first time it succeed with ant kafka-0.9, but failed to produce and consume message to kafka 0.9 broker (the error was failed to update metadata). so I changed different JAVA_HOME and different kafka library and other java library, but finally failed to compile with ICU error. 

Thanks a lot
Richard

**Comment by schulz2** [comment]
Hi Richard,

first of all, my recommendation to work with an appropriate Streams environment (according to your other error at least v4.2.0, better v4.2.1) still holds true. I don't understand how the compile can go through given that the "StateHandler" interface of Streams and toolkit do not match.
Furthermore, I don't understand why, when you encounter compilation errors, you start messing around with your JAVA_ENVIRONMENT. What, exactly, was the motivation behind that?

Kind regards
Norbert

**Comment by schulz2** [comment]
Hi Richard,
have you upgraded Streams or downgraded the toolkit and made progress?

Kind regards
Norbert
