### ISSUE TITLE
error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.messaging#332]
How to resolve the following error while execute ant kafka-0.9
compile:
    [javac] Compiling 66 source files to /home/streamsadmin/streamsx.messaging-5.3.1/com.ibm.streamsx.messaging/impl/java/bin
    [javac] /home/streamsadmin/streamsx.messaging-5.3.1/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/kafka/KafkaSource.java:478: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/home/streamsadmin/streamsx.messaging-5.3.1/com.ibm.streamsx.messaging/build.xml:68: The following error occurred while executing this line:
/home/streamsadmin/streamsx.messaging-5.3.1/com.ibm.streamsx.messaging/build.xml:104: Compile failed; see the compiler error output for details.

it will build successful after comment @Override. Does it function well with "@Override" commented?

**Comment by schulz2** [comment]
Hi sunruns,

here my comments:
Firstly, the "@Override" annotation is just a marker that one wants to override a super class method with the following method. On discovering that annotation the Java compiler checks for the existence of an appropriate method and warns if it doesn't. This helps in catching typos or wrong signatures. Commenting the annotation simply turns of this convenience function, but it will definitely not help with the intended class/method hierarchy. So, yes, you may get it compile clean, but - in this case - checkpointing will not work.
Secondly, the method you get the warning for is "regionCheckpointed" which has been introduced to the "StateHandler" interface with Streams v4.2. This interface definition is delivered with Streams. So you are now in the situation, that the Messaging toolkit v5.3.1 wants to override a method that your Streams v4.0.1 environment does not provide/request.

I recommend to update to a newer version of Streams or an older version of the toolkit.

Furthermore, I have to apologize, as I wanted - and already had - changed the required Streams version of the toolkit to a more appropriate version that would have avoided your current situation, but that change was overthrown by other colleagues. I will start the discussion again and probably end up with a cleaner requirements file.

Kind regards
Norbert

**Comment by schulz2** [comment]
Just checked:
Doesn't your info.xml file (in the toolkit) state that the minimum required version of Streams is 4.2.0?

**Comment by schulz2** [comment]
Hi Richard,
have you upgraded Streams or downgraded the toolkit and made progress?

Kind regards
Norbert
