### ISSUE TITLE
where can I find the logs produced by KafkaProducer and KafkaConsumer

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.messaging#334]
even I set the instance property instanceTrace.defaultLevel to trace, but there is nothing with Kafkaproducer and kafkaconsume in the /tmp../logs/..jobs/pec.out files.
Please help.

**Comment by schulz2** [comment]
Hi Richard,

as far as I understood it, the parameter you have been using is meant for monitoring the Streams' instance code, not anything that runs as a job in the PEs. Have you tried to enable tracing when you submit the job? Take a look at the '--trace' parameter of the 'streamtool submitjob' command:
https://www.ibm.com/support/knowledgecenter/SSCRJU_4.2.1/com.ibm.streams.ea.doc/streamtool/doc/submitjob.html

Furthermore, another pitfall is, that the job still must not be canceled when you do your 'getlogs'.

Hope that helps!

Kind regards
Norbert

**Comment by sunruns** [comment]
Hi Norbert,
     I submitjob with --tracing trace, but no any trace information of Kafkaconsumer and kafkaproducer in the log. I didn't cancel the job before I collect the logs.

**Comment by schulz2** [comment]
Glimpsed through the code and see enough tracing lines that you should at least see something. Are you working from the command line or in Streams Studio?

**Comment by sunruns** [comment]
sorry,maybe there are something wrong. and I close this issue.
