### ISSUE TITLE
Error: Could not find or load main class org.apache.log4j.net.JMSSink Caused by: java.lang.NoClassDefFoundError: javax/jms/MessageListener

### ISSUE THREAD

**Issue by sidhharth-developer** [IBMStreams/streamsx.messaging#360]

**Comment by RolefH** [comment]
Can you provide some more information please?
- Java stack trace
- PE trace file
- toolkit version

**Comment by RolefH** [comment]
If this is your first use of JMS within a Streams application, please consider to use the [JMS toolkit](https://github.com/IBMStreams/streamsx.jms) instead of the _streamsx.messaging_ toolkit, where the JMS support got deprecated.

**Comment by schubon** [comment]
Have you configured STREAMS_MESSAGING_AMQ_HOME or STREAMS_MESSAGING_WMQ_HOME environment variables, as described here:
https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.3.0/com.ibm.streams.toolkits.doc/spldoc/dita/tk$com.ibm.streamsx.messaging/tk$com.ibm.streamsx.messaging$1.html

**Comment by sidhharth-developer** [comment]
okay . now it works . Thanks for all .

**Comment by 18981a04h0123** [comment]
i am fresher to java i am facing same error - Error: Could not find or load main class org.apache.log4j.net.JMSSink
how  can i solve this pl explain in basic and simple way
