### ISSUE TITLE
The Readme needs to be updated to say the toolkit is deprecated

### ISSUE THREAD

**Issue by schubon** [IBMStreams/streamsx.messaging#361]
The Readme needs to be updated to say the toolkit is deprecated/out of service and update to include JMS as removed.
 
https://github.com/IBMStreams/streamsx.messaging#readme-----ibmstreamsstreamsxmessaging

Moreover there is a lot of documentation that needs to be updated if the toolkit is deprecated.
Messaging toolkit home page
http://ibmstreams.github.io/streamsx.messaging/
 
I would like to update the pages below to point to new documentation or mark as deprecated, but I do not know if they are still up to date.
 
JMS getting started: is there an equivalent documentation:
http://ibmstreams.github.io/streamsx.documentation/docs/4.2/messaging/jms-operators-getting-started/
 
Websphere MQ
http://ibmstreams.github.io/streamsx.documentation/docs/4.2/messaging/mq-create-objects-bindings-sample/

**Comment by schubon** [comment]
@natashadsilva 
You wrote you would like to update the following pages:
http://ibmstreams.github.io/streamsx.documentation/docs/4.2/messaging/jms-operators-getting-started/
http://ibmstreams.github.io/streamsx.documentation/docs/4.2/messaging/mq-create-objects-bindings-sample/

I think these need only updates for the toolkit names to reflect the new JMS toolkit. The configuration steps are still valid, as I haven't had the time to update the configuration/authentication methods in the JMS toolkit yet.

**Comment by schubon** [comment]
@natashadsilva 
Neccessary updates on https://ibmstreams.github.io/streamsx.documentation/docs/4.1/messaging/jms-operators-getting-started/ :

1. Sentence 'Messaging Toolkit - a official version of the toolkit is shipped with Streams or download it from IBM Streams GitHub Messaging Toolkit Repository' schould refer to JMS Toolkit and point to: https://github.com/IBMStreams/streamsx.jms 
2. Sentence 'echo "export STREAMS_SPLPATH=$STREAMS_INSTALL/toolkits/com.ibm.streamsx.messaging" >> /home/streamsadmin/.bashrc' should become 'echo "export STREAMS_SPLPATH=$STREAMS_INSTALL/toolkits/com.ibm.streamsx.jms" >> /home/streamsadmin/.bashrc'
3. Sentence 'sc -t $STREAMS_INSTALL/toolkits/com.ibm.streamsx.messaging -M MyMain' should become 'sc -t $STREAMS_INSTALL/toolkits/com.ibm.streamsx.jms -M MyMain'
4. Every 'messaging toolkit' should become 'JMS toolkit'
5. Every 'com.ibm.streamsx.messaging.jms' should become 'com.ibm.streamsx.jms'

**Comment by schubon** [comment]
@natashadsilva 
For the Kafka Operators document here https://ibmstreams.github.io/streamsx.documentation/docs/4.1/messaging/kafka-operators-getting-started/, I see the following changes:

1. Every 'Messaging Toolkit' should becom 'Kafka Toolkit' (probably removing version info while at it?)
2. Sentence 'Messaging Toolkit 4.0+ - You can download it from the IBM Streams GitHub Messaging Toolkit Repository Release Page.' should become 'Kafka Toolkit - You can download it from the IBM Streams GitHub Kafka Toolkit Repository Release Page.' with the link updated to 'https://github.com/IBMStreams/streamsx.kafka/releases'
3. 'com.ibm.streamsx.messaging.kafka::' should become 'com.ibm.streamsx.kafka::'
4. 'com.ibm.streamsx.messaging' should become 'com.ibm.streamsx.kafka'
5. 'KafkaSample' is now at https://github.com/IBMStreams/streamsx.kafka/tree/develop/samples/KafkaSample
6. There is no 'KafkaConsistentRegionConsumerSimple' anymore. Instead there are https://github.com/IBMStreams/streamsx.kafka/tree/develop/samples/KafkaCRTransactionalProducer and https://github.com/IBMStreams/streamsx.kafka/tree/develop/samples/KafkaConsumerGroupWithConsistentRegion
7. 'Streams Messaging Toolkit SPLDoc' should become 'Streams Kafka Toolkit SPLDoc' and point to https://ibmstreams.github.io/streamsx.kafka/doc/spldoc/html/

**Comment by schubon** [comment]
The document https://github.com/IBMStreams/streamsx.messaging/wiki/Getting-Started-with-Toolkit-Development and its sibling documents can stay unchanged, as these are describing the Messaging Toolkit per se and reside in the repository that is deprecated anyways, correct?

**Comment by natashadsilva** [comment]
hi Norbert,
Thank you for this info. I'm a bit confused by all the minor details; do you think you could update pages yourself? It is easy, you just click "Edit me " in the page you want to update, edit the page,  and when you save, it will create a PR to merge the changes you when you are done.
Thank you.

**Comment by schubon** [comment]
Updated https://ibmstreams.github.io/streamsx.documentation/docs/4.2/messaging/jms-operators-getting-started/

**Comment by schubon** [comment]
Updated https://ibmstreams.github.io/streamsx.documentation/docs/4.2/messaging/mq-create-objects-bindings-sample/

**Comment by schubon** [comment]
Updated https://ibmstreams.github.io/streamsx.documentation/docs/4.1/messaging/jms-operators-getting-started/

**Comment by schubon** [comment]
Updated some parts of https://ibmstreams.github.io/streamsx.documentation/docs/4.1/messaging/kafka-operators-getting-started/, but ...

The sections **Consistent Regions** and **Parallel Consuming** need a major work-over as the referred-to samples do not exist anymore. If I remember correctly, when James started the new Kafka Toolkit from scratch he changed how consistent region is implemented.

@RolefH: I think I need some help on that.

**Comment by schubon** [comment]
@natashadsilva 
- Can you take a look at the updates, please?
- These documents reside under different Streams version branches, and thus some content is duplicated. Furthermore, these documents describe more what you need to do in a (or some) toolkit(s), which doesn't always change with a new Streams version. Is there a chance to change the documents folder structure from, for example, "...//ibmstreams.github.io/streamsx.documentation/docs/4.1/messaging/jms-operators-getting-started/" to something like "...//ibmstreams.github.io/streamsx.documentation/docs/toolkits/jms/jms-operators-getting-started/"?

**Comment by natashadsilva** [comment]
Hi Norbert,
Thank you so much for looking at this.
The documentation is separated by version so that it matches what is included in that specific version of Streams. 

So, what we usually do (e.g. for the Python toolkit which is always updated) is to keep the old content so that if someone is using the messaging toolkit from 4.2 or 4.1 the instructions will match that version of the toolkit, just in case they are not able to upgrade for some reason. 

Then the 4.1 and 4.2 documentation can have a notice saying that the toolkit is deprecated and link to the latest.
Finally we have the documentation for the latest version of the toolkit in a new directory, like you suggested. So, do you mind reverting the 4.x changes and then putting the new content in a new folder? I'm sorry for the inconvenience, I should have mentioned this before.

Keeping the old content also makes sure that we don't have any broken links.

**Comment by schubon** [comment]
Hi @natashadsilva ,
that is very unsatisfying, I have to confess. 
So you want me to revert all those changes and instead create new documents (better copy current docs before reverting). Is that correct?

I'll see when I have time for that, as I'm currently preparing a customer project.

**Comment by schubon** [comment]
Saved the new versions of the documents on my laptop's HD

**Comment by schubon** [comment]
Rverted the four commits that updated the documentation.

**Comment by schubon** [comment]
Hi @natashadsilva ,

I need you to propose, or better: prepare in streamsx.documentation, the document structure to which the new versions of the documents shall be copied.

Assigning this issue to you now, please, re-assign it to me when you are done.

Thanks!

**Comment by natashadsilva** [comment]
@schubon I am just seeing your messages. Sorry  again for the extra work. The structure we have been following is having a folder per component under `/docs`.  Leave the rest of the updates to me. I will merge back in your new changes soon, as I am working on other doc updates. Thank you again.

**Comment by schubon** [comment]
[jms-operators-getting-started.md.txt](https://github.com/IBMStreams/streamsx.messaging/files/4614531/jms-operators-getting-started.md.txt)
[kafka-operators-getting-started.md.txt](https://github.com/IBMStreams/streamsx.messaging/files/4614532/kafka-operators-getting-started.md.txt)
[mq-create-objects-bindings-sample.md.txt](https://github.com/IBMStreams/streamsx.messaging/files/4614533/mq-create-objects-bindings-sample.md.txt)

**Comment by schubon** [comment]
Attached the saved documents, so you may just copy them into the new place. Please, ping me when these are at their new place so I can go over them again. Thank you very much!

**Comment by schubon** [comment]
Hi @natashadsilva, do you remember if the documents mentioned above were incorporated into the new documentation, so we can close this issue here?

**Comment by natashadsilva** [comment]
Yes I incorporated them, thanks.

**Comment by schubon** [comment]
Thank you very much, Natasha. Closing this issue now.
