### ISSUE TITLE
Enhance connection mechanism with Kafka operators

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#37]
With the messaging toolkit operators, all operators support the following connection mechanism.  I am wondering if it makes sense for the Kafka operators to also support these:

1)  support for connection document 
2)  support for connection and reconnection policy
3)  dynamic update for connection - i.e. ability to switch Kafka servers on the fly with a control signal.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
