### ISSUE TITLE
What format do the new MQTT operators use for the messaging?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#57]
The MQTT operators in the Streams 3.2.0 product allow the specification of the format used for messages bin, or block.

This parameter is not available in the new toolkit, for the Streams 3.2.2. open beta, so if i want to have messages that can be sent to a 3.2.0 instance or a 3.2.2 beta instance, what format should I use in the execution of the 3.2.0 operators?

I assume it is block?

**Comment by chanskw** [comment]
fixed
