### ISSUE TITLE
Add consistent region support

### ISSUE THREAD

**Issue by rohitsw** [IBMStreams/streamsx.messaging#71]
Kafka Operators:
KafkaProducer will not be allowed at the beginning of a consistent region
KafkaConsumer will not be allowed in a consistent region. It is technically possible to use a low level Kafka API and support some sort of replaying of data for consistent regions, however Kafka documentation mentions that replay support will be added in the recommended high-level API sometime in the near future. Consistent region support can then be re-evaluated at that point

**Comment by chanskw** [comment]
I copied the description here.. as we are also adding support for JMS, MQTT and XMS

https://github.com/IBMStreams/streamsx.messaging/wiki/Consistent-Region-Support-for-Messaging-Toolkit
