### ISSUE TITLE
MQTT: MQTTSource loses tuples when topic submitted with a control port 

### ISSUE THREAD

**Issue by kmarsden** [IBMStreams/streamsx.messaging#77]
The following code shows the issue:

namespace application ;

use com.ibm.streamsx.messaging.mqtt::\* ;

composite Main
{

```
param
    expression<rstring> $serverUri : getSubmissionTimeValue("serverUri") ;
type
    PersonSchema = int32 id, rstring fname, rstring lname, int32 age,
        rstring gender, float32 score, float64 total ;
graph
    stream<PersonSchema> InputData = Beacon()
    {
        param
            initDelay : 5.0 ;
            iterations : 100000u ;
        output
            InputData : id =(int32) IterationCount(), fname = "Cristiana", lname =
                "Chitic", age = 30, gender = "F", score =(float32) 93.2, total = 664.4 ;
    }

    /*
     * Convert input data to blob in csv format.
     */
    (stream<blob msg> CsvMsg) as FormatMsg = Format(InputData)
    {
        param
            format : csv ;
        output
            CsvMsg : msg = Output() ;
    }

    () as MQTTSink_6 = MQTTSink(CsvMsg as inPort0Alias)
    {
        param
            serverURI : $serverUri ;
            topic : "demo/cars/CSV/A" ;
    }

    stream<MQTTSourceUpdate.ControlPortType> ControlOp_out1 =
        Custom()
    {
        logic
            onProcess :


            {
            // empty mqtt config because we are not changing connection information.
                map<rstring, rstring> emptyMqttConfig = { "" : "" } ;

                // topics
                MQTTSourceUpdate.TopicsUpdateDesc set1 = { action =
                    MQTTSourceUpdate.REPLACE, topics = [ "demo/cars/CSV/+" ], qos = 0u } ;

                // construct tuple to submit
                tuple<MQTTSourceUpdate.ControlPortType> tupleToSubmit = { mqttConfig =
                    emptyMqttConfig, topic = [ set1 ] } ;

                submit(tupleToSubmit, ControlOp_out1) ;
            }

    }

     // switch this line to see it work without control port
    // stream<blob msg,rstring topic> mqttMsgRaw as dataStream = MQTTSource( ) 
    stream<blob msg, rstring topic> mqttMsgRaw as dataStream =
        MQTTSource(ControlOp_out1)
    {
        param
            serverURI : $serverUri;
            // switch line below to see it work without control port.
            topics : "empty" ; //empty initial
            //  * topics : "demo/cars/CSV/+";
            topicOutAttrName : "topic" ;
            qos : 0 ;
        config
            tracing : debug ;
    }

    () as cus_sink = Custom(mqttMsgRaw)
    {
        logic
            onTuple mqttMsgRaw :
            {
                printStringLn("debugging1 topic = " + topic) ;
            }

    }
```

}

Below is the  description.

at the time of initialization, the mqttsource operator has a dummy topic,  which then is replaced by a list of topics by the control port.  However,  when I do that,  the mqttsource operator does not seem to submit any data to the output port.  Debugging shows that the operator does receive data from the server,  yet it doesn't attempt to submit.  It appears as though the thread that does the submit() call doesn't work in this case.   In absence of control port,  if I submit the right topic at the time of initialization itself, it works fine.

**Comment by chanskw** [comment]
Rejecting.  Based on Raju's feedback.  This is an user error.  The problem is that the control signal sends in a final punct, which causes the application to end.

**Comment by koteibb** [comment]
Please  i have got the same  problem, can you please tell me how you fix it ?

**Comment by ddebrunner** [comment]
I would say this is a bug in MQTTSource, the final punct from the control port should **not** cause the MQTTSource output port to become finalized, the operator still has work to do.

So the behaviour should be regardless of any control port finalization (unless there is an explicit control instruction to stop sending messages) the operator continues to read messages and submit tuples.

**Comment by koteibb** [comment]
Ok thanks ddebrunner for your answer, can you tell me please if this bug has been correted ? If no do you have any altrnative solution ?

**Comment by ddebrunner** [comment]
Ensure the control stream does not send a final marker, so it comes from an operator that does not provide a finite stream.

How are you generating the control tuples?

**Comment by koteibb** [comment]
like that : 
set1 = { action = MQTTSourceUpdate.ADD, topics = [ newTopSubscriptionMessageSplit[1] ], qos = 0u };
tuple<MQTTSourceUpdate.ControlPortType> tupleToSubmit = { mqttConfig = emptyMqttConfig, topic = [ set1 ] };
submit(tupleToSubmit, ConfigMQTT);

**Comment by schubon** [comment]
Customers are already using the new toolkit https://github.com/IBMStreams/streamsx.mqtt
