### ISSUE TITLE
MQTTSink operator does not give compile warning when it's in consistent region and has control input port

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#97]
I see that we have the code implemented, but the compile warning is still not shown.
We need to investigate.

**Comment by chanskw** [comment]
@conglisc please investigate

**Comment by conglisc** [comment]
This issue is due to that the logger being used is a trace logger, a new logger is now defined pointing to SPL Log Facility and warning messaging is getting printed out via this new logger object.

**Comment by chanskw** [comment]
Fixed
