### ISSUE TITLE
Add Consistent Region support for JMSSource

### ISSUE THREAD

**Issue by KevinFoster925** [IBMStreams/streamsx.messaging#99]
JMS is a popular method for ingesting data into Streams. Would be good to be able to include the JMSSource operator (should be feasible) and JMSSink (might be feasible?).

**Comment by chanskw** [comment]
JMSSink already support consistent region
JMSSource does not, and it is recommended for it to be used in conjunction with ReplayableStart operator from Standard Toolkit.  

One way to support consistent region with JMSSource is to add support for transaction when dealing with ActiveMQ and Websphere MQ.  However, transaction tends to be slower and may not be able to handle the message rate from Streams.  

But Yes, this is something we should look at.

**Comment by conglisc** [comment]
Consistent Region support is added to JMSSource, closing this ticket.
